### ISSUE TITLE
ZFS Thin Provisioning

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#1]
# Feature Request
## Description
Hello, do you plan to support zfs thin volumes?
Basically it is just about specifying `-s` flag when creating zfs volume, example:

```
zfs create -s -V 500G data/thinvolume_00000
```

## Use case
It would be nice for save space on the nodes.

## Interface Changes

I think this option may be set via 
```
linstor storage-pool set-property node1 myzfspool sparse true
```

**Comment by raltnoeder** [comment]
This is planned for a future release. The first version of LINSTOR that works with thin provisioning in practice was tested for the first time internally at LINBIT yesterday, but is not yet released. Earlier versions effectively allocate all the space on SyncTarget volumes when DRBD performs the initial resync.
Mixing fat provisioned and thin provisioned volumes in one resource is supported.
Mixing the provisioning mode of the same volume on different nodes is not supported.
