### ISSUE TITLE
Can't upgrade to 1.3.0 --> 1.4.1

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#100]
```
LINSTOR, Module Controller
Version:            1.4.1 (d4c4d5b5b5916735ca398d0db7f6b2e43739715a)
Build time:         2020-01-16T07:44:40+00:00
Java Version:       11
Java VM:            Private Build, Version 11.0.5+10-post-Ubuntu-0ubuntu1.118.04
Operating system:   Linux, Version 4.15.18-12-pve
Environment:        amd64, 1 processors, 7756 MiB memory reserved for allocations
System components initialization in progress
17:02:15.993 [main] INFO  LINSTOR/Controller - SYSTEM - Log directory set to: '/logs'
17:02:16.349 [main] INFO  LINSTOR/Controller - SYSTEM - Linstor configuration file loaded from '/config/linstor.toml'.
17:02:16.351 [Main] INFO  LINSTOR/Controller - SYSTEM - Loading API classes started.
17:02:18.270 [Main] INFO  LINSTOR/Controller - SYSTEM - API classes loading finished: 1918ms
17:02:18.270 [Main] INFO  LINSTOR/Controller - SYSTEM - Dependency injection started.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/linstor-server/lib/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
17:02:21.581 [Main] INFO  LINSTOR/Controller - SYSTEM - Dependency injection finished: 3311ms
17:02:22.346 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing authentication subsystem
17:02:22.780 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing the database connection pool
17:02:23.438 [Main] INFO  org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 5.2.4 by Boxfuse
17:02:23.478 [Main] INFO  org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:postgresql://linstor-db-stolon-proxy/linstor2 (PostgreSQL 10.5)
17:02:23.721 [Main] INFO  org.flywaydb.core.internal.command.DbValidate - Successfully validated 35 migrations (execution time 00:00.078s)
17:02:23.760 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Current version of schema "LINSTOR": 2019.11.12.01.01
17:02:23.761 [Main] WARN  org.flywaydb.core.internal.command.DbMigrate - outOfOrder mode is active. Migration of schema "LINSTOR" may not be reproducible.
17:02:23.764 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema "LINSTOR" to version 2019.11.21.01.01 - Unifies resources and snapshots
17:02:26.059 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema "LINSTOR" to version 2019.12.03.01.01 - Add new column LAYER_RESOURCE_SUSPENDED to LAYER_RESOURCE_IDS
17:02:26.174 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema "LINSTOR" to version 2019.12.04.01.01 - Delete orphaned layer resource ids
17:02:26.215 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema "LINSTOR" to version 2019.12.11.01.01 - Remove swordfish table
17:02:26.248 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Successfully applied 4 migrations to schema "LINSTOR" (execution time 00:02.510s)
17:02:26.263 [Main] INFO  LINSTOR/Controller - SYSTEM - Loading security objects
17:02:26.311 [Main] INFO  LINSTOR/Controller - SYSTEM - Current security level is NO_SECURITY
17:02:26.381 [Main] INFO  LINSTOR/Controller - SYSTEM - Core objects load from database is in progress
17:02:38.372 [Main] ERROR LINSTOR/Controller - SYSTEM - An exception occurred while creating layer data [Report number 5E21E896-00000-000000]
17:02:38.375 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutdown in progress
17:02:38.378 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'DatabaseService' of type DatabaseService
17:02:38.385 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'DatabaseService' to complete shutdown
17:02:38.385 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'TaskScheduleService' of type TaskScheduleService
17:02:38.385 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'TaskScheduleService' to complete shutdown
17:02:38.386 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'TimerEventService' of type TimerEventService
17:02:38.386 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'TimerEventService' to complete shutdown
17:02:38.386 [Thread-0] INFO  LINSTOR/Controller - SYSTEM - Shutdown complete
```

[ErrorReport-5E21E896-00000-000000.log](https://github.com/LINBIT/linstor-server/files/4077849/ErrorReport-5E21E896-00000-000000.log)

Somthing wrong with the THIN_LVM:
```
Storage driver 'LVM_THIN' not allowed for volume.
```

**Comment by ghernadi** [comment]
That is interesting.. The exception is thrown when the controller is trying to create the layer data for a volume while there is a peer-volume placed in a different storage pool kind (`LVM_THIN` vs something else, maybe `LVM`, `ZFS`, ...).
Although we should finally get rid of this limitation (there are a few ways to achieve that, but there were always more important tasks on our list), but as this exception obviously did not occur for you in 1.3.0, I would be still very interested why it does in 1.4.1.

Is it possible to send me a dump of your database? Ideally the backuped 1.3.0 as well as the migrated 1.4.1.   
If you dont want to post it publicly available, feel free to send it to me via email.

**Comment by ghernadi** [comment]
Good news is that I have found the issue for `pvc-3a5130d9-b93e-4a6a-8c88-3aae7f7c15bf` and I assume its the same issue as for the other two resources. 

Another good news is that if you want me to fix those entries in your database I guess I could send you a simple diff of your dump (without having to delete those resources) if you'd like.

Bad news is that there are more complicated cases which might have been triggered by other users that prevent me writing a general migration that fixes this issue for all scenarios. So I guess I have to think a bit longer / harder about a general solution for this issue.

**Comment by kvaps** [comment]
Good news!
Yes, please send me a fix, I'm going to migrate production cluster soon

**Comment by ghernadi** [comment]
As long as you do **NOT** have NVMe in the setup, executing this SQL should fix your database:

`UPDATE RESOURCES SET RESOURCE_FLAGS = 260 WHERE RESOURCE_FLAGS = 4;`

The issue here is basically that we overlooked a place where we did not properly applied the `DRBD_DISKLESS` (256) flag where before a simple `DISKLESS` (4) flag was sufficient. As a standalone `DISKLESS` flag is already deprecated, it should be save to run this SQL so that all affected resources will get both flags (`DISKLESS` and `DRBD_DISKLESS`) - which is also intentional as long as we do not completely remove the `DISKLESS` flag but keep it as deprecated for compatibility reasons.

Having written this short explanation, I guess I also have figured a way to for a general solution :)

As there are also other small things we need to fix internally, we might be releasing a `v1.4.2` soon-ish, which will include the mentioned solution for all scenarios.

Please close this issue once you have verified the solution works.

**Comment by kvaps** [comment]
Confirm, this is working for me:

```
set search_path="LINSTOR",public;
UPDATE RESOURCES SET RESOURCE_FLAGS = 260 WHERE RESOURCE_FLAGS = 4;
```

I'll update production cluster soon, I'll reopen the issue if I will have a trouble.

@ghernadi many thanks for explanation!

**Comment by ghernadi** [comment]
Just for the record: 

kvaps and me figured out that this issue was most likely based on the broken migration and missing proper rollback.

That means: If Linstor fails to migrate and you downgrade the software, please also make sure that you also fully revert the database before starting the old version again.
