### ISSUE TITLE
linstor resource create command silently fails if /var/lib/linstor.d/linstor_common.conf is not present, or content is wrong

### ISSUE THREAD

**Issue by gy-lehel** [LINBIT/linstor-server#12]
Executing linstor resource create will silently fail if /var/lib/linstor.d/linstor_common.conf is not present on all satellites, or its content can not be parsed properly.

**Comment by gy-lehel** [comment]
ERROR REPORT 5B9A4EE9-000002                                                                                                                                                                                                         [108/4129]
                                                                                            
============================================================                                                           
                                                           
Application:                        LINBIT® LINSTOR        
Module:                             Satellite              
Version:                            0.6.3                                                                                                                                                                                                      
Build ID:                           d608e73ee81aba96ced64e6358244994192341d1   
Build time:                         2018-09-10T13:40:48+00:00                  
Error time:                         2018-09-13 15:10:13                        
Node:                               storage-drbd-test-vm4                                         
                                                                                                                       
============================================================                                                           
                                                                                                                          
Reported error:                                                                           
===============                                            
                                                           
Description:                                                                                                           
    Operations on resource 'kubernetes' were aborted                                                                   
Cause:                      
    Verification of resource file failed                                                                               
Additional information:                                     
    The error reported by the runtime environment or operating system is:
    The external command 'drbdadm' exited with error code 10
                                             
Category:                           LinStorException                                                                   
Class name:                         ResourceException                                                                  
Class canonical name:               com.linbit.linstor.core.DrbdDeviceHandler.ResourceException                        
Generated at:                       Method 'createResourceConfiguration', Source file 'DrbdDeviceHandler.java', Line #1320
                                                                                                                       
Error message:                      Generated resource file for resource 'kubernetes' is invalid.                      
                                                                                                                       
Error context:                                                                                                                                                                                                                                 
    Generated resource file for resource 'kubernetes' is invalid.                                                      
               
Call backtrace:
                                                           
    Method                                   Native Class:Line number
    createResourceConfiguration              N      com.linbit.linstor.core.DrbdDeviceHandler:1320
    createResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1048
    dispatchResource                         N      com.linbit.linstor.core.DrbdDeviceHandler:307
    run                                      N      com.linbit.linstor.core.DeviceManagerImpl$DeviceHandlerInvocation:1328
    run                                      N      com.linbit.WorkerPool$WorkerThread:179

Caused by:
==========

Description:
    Execution of the external command 'drbdadm' failed.
Cause:
    The external command exited with error code 10.
Correction:
    - Check whether the external program is operating properly.
    - Check whether the command line is correct.
      Contact a system administrator or a developer if the command line is no longer valid
      for the installed version of the external program.
Additional information:
    The full command line executed was:
    drbdadm --config-to-test /var/lib/linstor.d/kubernetes.res_tmp --config-to-exclude /var/lib/linstor.d/kubernetes.res sh-nop

    The external command sent the following output data:


    The external command sent the follwing error information:
    /var/lib/linstor.d/kubernetes.res_tmp:9: Failed to open template file 'linstor_common.conf'.


Category:                           LinStorException
Class name:                         ExtCmdFailedException
Class canonical name:               com.linbit.extproc.ExtCmdFailedException
Generated at:                       Method 'execute', Source file 'DrbdAdm.java', Line #445

Error message:                      The external command 'drbdadm' exited with error code 10

                                                                                                                                                                                                                                      [35/4129]

Call backtrace:

    Method                                   Native Class:Line number
    execute                                  N      com.linbit.drbd.DrbdAdm:445
    execute                                  N      com.linbit.drbd.DrbdAdm:431
    checkResFile                             N      com.linbit.drbd.DrbdAdm:334
    createResourceConfiguration              N      com.linbit.linstor.core.DrbdDeviceHandler:1313
    createResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1048
    dispatchResource                         N      com.linbit.linstor.core.DrbdDeviceHandler:307
    run                                      N      com.linbit.linstor.core.DeviceManagerImpl$DeviceHandlerInvocation:1328
    run                                      N      com.linbit.WorkerPool$WorkerThread:179


END OF ERROR REPORT.

ERROR REPORT 5B9A4EE9-000002

============================================================

Application:                        LINBIT® LINSTOR
Module:                             Satellite
Version:                            0.6.3
Build ID:                           d608e73ee81aba96ced64e6358244994192341d1
Build time:                         2018-09-10T13:40:48+00:00
Error time:                         2018-09-13 15:11:05
Node:                               storage-drbd-test-vm1

============================================================

Reported error:
===============

Description:
    Operations on resource 'kubernetes' were aborted
Cause:
    Verification of resource file failed
Additional information:
    The error reported by the runtime environment or operating system is:
    The external command 'drbdadm' exited with error code 10

Category:                           LinStorException
Class name:                         ResourceException
Class canonical name:               com.linbit.linstor.core.DrbdDeviceHandler.ResourceException
Generated at:                       Method 'createResourceConfiguration', Source file 'DrbdDeviceHandler.java', Line #1320

Error message:                      Generated resource file for resource 'kubernetes' is invalid.

Error context:
    Generated resource file for resource 'kubernetes' is invalid.

Call backtrace:

    Method                                   Native Class:Line number
    createResourceConfiguration              N      com.linbit.linstor.core.DrbdDeviceHandler:1320
    createResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1048
    dispatchResource                         N      com.linbit.linstor.core.DrbdDeviceHandler:307
    run                                      N      com.linbit.linstor.core.DeviceManagerImpl$DeviceHandlerInvocation:1328
    run                                      N      com.linbit.WorkerPool$WorkerThread:179

Caused by:
==========

Description:
    Execution of the external command 'drbdadm' failed.
Cause:
    The external command exited with error code 10.
Correction:
    - Check whether the external program is operating properly.
    - Check whether the command line is correct.
      Contact a system administrator or a developer if the command line is no longer valid
      for the installed version of the external program.
Additional information:
    The full command line executed was:
    drbdadm --config-to-test /var/lib/linstor.d/kubernetes.res_tmp --config-to-exclude /var/lib/linstor.d/kubernetes.res sh-nop

    The external command sent the following output data:


    The external command sent the follwing error information:
    /var/lib/linstor.d/kubernetes.res_tmp:9: Failed to open template file 'linstor_common.conf'.


Category:                           LinStorException
Class name:                         ExtCmdFailedException
Class canonical name:               com.linbit.extproc.ExtCmdFailedException
Generated at:                       Method 'execute', Source file 'DrbdAdm.java', Line #445

Error message:                      The external command 'drbdadm' exited with error code 10


Call backtrace:

    Method                                   Native Class:Line number
    execute                                  N      com.linbit.drbd.DrbdAdm:445
    execute                                  N      com.linbit.drbd.DrbdAdm:431
    checkResFile                             N      com.linbit.drbd.DrbdAdm:334
    createResourceConfiguration              N      com.linbit.linstor.core.DrbdDeviceHandler:1313
    createResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1048
    dispatchResource                         N      com.linbit.linstor.core.DrbdDeviceHandler:307
    run                                      N      com.linbit.linstor.core.DeviceManagerImpl$DeviceHandlerInvocation:1328
    run                                      N      com.linbit.WorkerPool$WorkerThread:179


END OF ERROR REPORT.

**Comment by gy-lehel** [comment]
[error.txt](https://github.com/LINBIT/linstor-server/files/2382431/error.txt)

**Comment by rp-** [comment]
duplicate to issue #9 
but thanks for the report
