### ISSUE TITLE
Feature request: Ability to change resource group for resource definition

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#125]
Hi, we have a lot of resources created using old drivers and cli, without resource groups, thus all of them in `DfltRscGrp` right now.

In order to start using resource groups we need ability to move old resource definitions to newly created resource groups.

**Comment by ghernadi** [comment]
Agreed. This is already on our todo-list. Will keep this open until the feature is released.

**Comment by kvaps** [comment]
ok it seems the requested feature was already implemented in some release, I have it working on my `1.11.0``
```
linstor rd modify one-vm-9240-disk-2 --resource-group opennebula-1
```

thank you, closing
