### ISSUE TITLE
Possible data loss during reallocating replicas

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#133]
Hi, I still didn't found exact steps to reproduce but we're facing with this issue quite often, we facing eith data loss in the next situation:

Volume have **2 data resources** and **1 diskless resource** which is actually Primary:
```
+-------------------------------------------------------------+
| ResourceName      | Node | Port | Usage  | Conns |    State |
|=============================================================|
| one-vm-403-disk-0 | m1c5 | 7338 | Unused | Ok    | UpToDate |
| one-vm-403-disk-0 | m1c6 | 7338 | Unused | Ok    | UpToDate |
| one-vm-403-disk-0 | m1c7 | 7338 | InUse  | Ok    | Diskless |
+-------------------------------------------------------------+
```

Sometimes our storage nodes are running out of space, and we forced to reallocate some replicas to another nodes, we have two cases for doing this:

* Delete and recreate one of storage replicas, eg:

  ```
  linstor r d m1c5 one-vm-403-disk-0
  linstor r c m1c4 one-vm-403-disk-0
  ```
  \- in most cases we're facing with the data loss

* Run verify, then create new replica, then remove old one: 

  ```
  drbdadm verify one-vm-403-disk-0
  linstor r c m1c4 one-vm-403-disk-0
  linstor r d m1c5 one-vm-403-disk-0
  ```
  \- usually there is no data loss in this case

I was thinking that it might be connected with the [`errorwhenfull`](https://www.systutorials.com/docs/linux/man/7-lvmthin/#lbAX) option for LVM thinpools which is set to `no` by default.

But last case was happenв even without pool overfilling.

My question is: maybe do you have some recommendations for doing this, and any ideas why it might be happen, how can I catch this bug?

Thanks a lot!

**Comment by ghernadi** [comment]
1) how do you verify you lost data?
2) how old are those resoures? are we talking about hours, days, months? I actually mean Linstor-resources, not DRBD-resources
3) in what state is the DRBD-resource after you lost data?

**Comment by kvaps** [comment]
1. Customers complaining on corrupted filesystem after the change, errors like `Structure needs cleaning`, corrupted binary files, system does not boot, `fsck -y` shows a lot of fixes but they not making much sense.
2. Usually this is old resources created few months ago
3. They are `UpToDate`

**Comment by ghernadi** [comment]
What DRBD version are you using? 

`cat /proc/drbd`

**Comment by kvaps** [comment]
```
version: 9.0.21-1 (api:2/proto:86-116)
GIT-hash: 449d6bf22b01af7d14a297a4ed3e281aa84c94a5 build by @runner-vy7cbjev-project-69-concurrent-1dkv59, 2020-01-21 10:39:34
Transports (api:16): tcp (9.0.21-1)
```

but it was happening even on older ones:
ref https://lists.linbit.com/pipermail/drbd-user/2019-November/025359.html

**Comment by Philipp-Reisner** [comment]
Gabor's line of thinking is: Maybe it is already fixed in DRBD 9.0.22 . 
The issue with 9.0.22 is that it introduced a locking bug that was fixed later here: https://github.com/LINBIT/drbd/commit/63d37a6a52d9134d8afecfeb4a9430023dbb968e

Usually, you should not hit that in a linstor cluster. But my fellow linstor devs managed to hit it with their test-suite.

Interesting is the aspect that a verify reduces the likeliness to hit the issue. So ideally you would roll out at DBRD git 63d37a6a52d9... and see if you can reproduce the issue or if it is already gone.

**Comment by kvaps** [comment]
> Interesting is the aspect that a verify reduces the likeliness to hit the issue.

It can be either verify or the fact that we're creating new replica before removing another one in second case. Since bug is happening randomely I had no an opportunity to check what exactly.

> So ideally you would roll out at DBRD git 63d37a6a52d9... and see if you can reproduce the issue or if it is already gone.

Sure, we're already planning an upgrade, I'll try to reproduce it there.

**Comment by kvaps** [comment]
Meanwhile, is there any recommendations on `error_when_full` option for thin-lvm pools?
Not sure, but I think it might be highly recommended to all the LINSTOR users:

```
       While waiting to be extended, the thin pool will queue writes for up
       to 60 seconds (the default).  If data space has not been extended
       after this time, the queued writes will return an error to the
       caller, e.g. the file system.  This can result in file system
       corruption for non-journaled file systems that may require repair.
       When a thin pool returns errors for writes to a thin LV, any file
       system is subject to losing unsynced user data.
```

**Comment by kvaps** [comment]
It seems it was really related to the old drbd version.
Most of resources were created since 9.0.19, and some of them still had an issues until I fully rewritten the drives by the following command:

```bash
dd if="$DEVICE" of="$DEVICE" status=progress bs=65536 conv=notrunc,sparse iflag=direct,fullblock oflag=direct
```

This problem does not appears on newer drbd versions (9.0.25 - 9.0.27)

Thank you! I'll close this issue for now.
