### ISSUE TITLE
Reset encryption passphrase

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#137]
Hi I had an experience to make a mistake while typing initial passphrase, now I cant unseal or remove it at all.
Is there any simple option for reinitialize encryption passphrase?

```bash
# linstor encryption create-passphrase
Passphrase: 
ERROR:
Description:
    Coult not create new crypt passphrase as it already exists
Cause:
    A passphrase was already defined
Correction:
    Use the crypt-modify-passphrase command instead of crypt-create-passphrase
```

```bash
# linstor encryption modify-passphrase
Old passphrase: 
New passphrase: 
ERROR:
Description:
    Could not restore master passphrase as the given old passphrase was incorrect
Cause:
    Wrong passphrase
Correction:
    Enter the correct passphrase
```

**Comment by ghernadi** [comment]
Well - if you already have encrypted volumes based on the old passphrase, you surely have a problem now.

To directly answer your question: No, linstor has no simply way of resetting the master-passphrase, as such a thing would completely make the whole encryption feature useless. 

We could think about an `forget-passphrase` api, but even if we add such a feature, it would only work if there are no encrypted volumes present (you will have to delete them first) as re-creating a master-passphrase would still not make them magically usable again.

For now, you will have to directly remove the following entries from the DB:
SQL:
```
DELETE FROM LINSTOR.PROPS_CONTAINERS WHERE PROPS_INSTANCE = '/CTRLCFG' AND PROP_KEY LIKE 'encrypted/%'
```
ETCD:
```
ETCDCTL_API=3 etcdctl del "/LINSTOR/PROPS_CONTAINERS//CTRLCFG:encrypted" --prefix
```

**Comment by kvaps** [comment]
Okay, I use PostgreSQL and this request solves my problem:

```sql
SET search_path TO "LINSTOR",public;
DELETE FROM PROPS_CONTAINERS WHERE PROPS_INSTANCE = '/CTRLCFG' AND PROP_KEY LIKE 'encrypted/%';
```

Should I close this issue, or you would implement such API?

**Comment by ghernadi** [comment]
I'll close this for now - if this issue appears more often or more people want us to implement such a `forget-passphrase`, we can reopen this issue anytime.
