### ISSUE TITLE
LINSTORPlugin.pm line 139

### ISSUE THREAD

**Issue by forfreeuser** [LINBIT/linstor-server#14]
After update:
```
Start-Date: 2018-09-17  08:16:21
Commandline: apt-get upgrade
Upgrade: linstor-common:amd64 (0.6.3-1, 0.6.4-1), linstor-satellite:amd64 (0.6.3-1, 0.6.4-1)
End-Date: 2018-09-17  08:16:24
```

Get errors of starting any VM with disk on drbdpool:

`TASK ERROR: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm line 139.`

**Comment by rp-** [comment]
could you manually run `linstor resource list` on the controller node?
and paste the output here?

**Comment by forfreeuser** [comment]
No, my controller node on drbdpool - can't run.

But, after reboot all nodes it working again.
