### ISSUE TITLE
Deadlock on reconnect the node 

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#141]
Hi, we have about 550 nodes, all of them were connected via SSL but now we faced with the deadlock of controller if some node is getting reconnected.

Initial startup is working fine and loads all the nodes, but if we restart one of satellite, our controller is getting stuck for any API operations connected with the node (in particular `linstor n l`, `linstor sp l`). later any other operations are stooping work too (eg `linstor c v`, `linstor rd l`).

While debugging I tried to switch all the nodes back to use Plain connector, but any time I see the same message in TRACE before controller is getting stuck:

```
[SslConnector] TRACE LINSTOR/Controller - SYSTEM - Peer Node: 'pve1', Background operation 'Auth' scope 'authenticting node 'pve1'' start
```

This message appears whether SSL is used or not.

**Comment by kvaps** [comment]
same #143 the problem persists on ubuntu xenial but debian stretch is working fine

**Comment by ghernadi** [comment]
We found some locking issue in our `ReconnectorTask` and trying to fix that. Hopefully that solves this issue. 

I will leave this open for verification this bug is gone after 1.7.1 is released.

**Comment by kvaps** [comment]
Hi, I just updated controller to 1.7.1 on debian stretch image, and it seems problem is still there, I've switched nodes to use SSL connection and got a deadlock again 🤔

**Comment by kvaps** [comment]
Hi, I just recompiled new docker images and started rolling update for our cluster (linstor version was not changed, SSL for satellites currently disabled), and got deadlock again:
```
LINSTOR, Module Controller
Version:            1.7.1 (6760637d6fae7a5862103ced4ea0ab0a758861f9)
Build time:         2020-05-15T08:20:00+00:00
Java Version:       11
Java VM:            Debian, Version 11.0.7+10-post-Debian-3deb10u1
Operating system:   Linux, Version 5.3.10-1-pve
Environment:        amd64, 1 processors, 29694 MiB memory reserved for allocations
System components initialization in progress
09:44:40.808 [main] INFO  LINSTOR/Controller - SYSTEM - Log directory set to: '/logs'
09:44:40.814 [Main] INFO  LINSTOR/Controller - SYSTEM - Loading API classes started.
09:44:41.807 [Main] INFO  LINSTOR/Controller - SYSTEM - API classes loading finished: 993ms
09:44:41.809 [Main] INFO  LINSTOR/Controller - SYSTEM - Dependency injection started.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/linstor-server/lib/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
09:44:45.037 [Main] INFO  LINSTOR/Controller - SYSTEM - Dependency injection finished: 3226ms
09:44:45.746 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing authentication subsystem
09:44:46.194 [Main] INFO  LINSTOR/Controller - SYSTEM - Starting service instance 'TimerEventService' of type TimerEventService
09:44:46.196 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing the database connection pool
09:44:46.858 [Main] WARN  org.flywaydb.core.api.Location - Use of dots (.) as path separators will be deprecated in Flyway 7. Path: com.linbit.linstor.dbcp.migration
09:44:46.868 [Main] INFO  org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 6.3.2 by Redgate
09:44:46.982 [Main] INFO  org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:postgresql://linstor-db-stolon-proxy/linstor2 (PostgreSQL 10.12)
09:44:47.081 [Main] INFO  org.flywaydb.core.internal.command.DbValidate - Successfully validated 42 migrations (execution time 00:00.063s)
09:44:47.100 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Current version of schema "LINSTOR": 2020.05.14.13.37
09:44:47.100 [Main] WARN  org.flywaydb.core.internal.command.DbMigrate - outOfOrder mode is active. Migration of schema "LINSTOR" may not be reproducible.
09:44:47.106 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Schema "LINSTOR" is up to date. No migration necessary.
09:44:47.138 [Main] INFO  LINSTOR/Controller - SYSTEM - Starting service instance 'DatabaseService' of type DatabaseService
09:44:47.138 [Main] INFO  LINSTOR/Controller - SYSTEM - Loading security objects
09:44:47.181 [Main] INFO  LINSTOR/Controller - SYSTEM - Current security level is NO_SECURITY
09:44:47.244 [Main] INFO  LINSTOR/Controller - SYSTEM - Core objects load from database is in progress
09:45:46.192 [Main] INFO  LINSTOR/Controller - SYSTEM - Core objects load from database completed
09:45:46.438 [Main] INFO  LINSTOR/Controller - SYSTEM - Starting service instance 'TaskScheduleService' of type TaskScheduleService
09:45:46.441 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing network communications services
09:45:46.442 [Main] WARN  LINSTOR/Controller - SYSTEM - The SSL network communication service 'DebugSslConnector' is missing the trustStor file (/config/ssl/certificates.jks)
09:45:46.447 [TaskScheduleService] INFO  LINSTOR/Controller - SYSTEM - LogArchive: Running log archive on directory: /logs
09:45:46.592 [TaskScheduleService] INFO  LINSTOR/Controller - SYSTEM - LogArchive: No logs to archive.
09:45:47.600 [Main] WARN  LINSTOR/Controller - SYSTEM - NetComService: Connector DebugSslConnector: Binding the socket to the IPv6 anylocal address failed, attempting fallback to IPv4
09:45:47.605 [Main] INFO  LINSTOR/Controller - SYSTEM - Created network communication service 'DebugSslConnector', bound to ::0:3373
09:45:47.609 [Main] INFO  LINSTOR/Controller - SYSTEM - Created network communication service 'PlainConnector', bound to 127.0.0.1:3376
09:45:47.609 [Main] WARN  LINSTOR/Controller - SYSTEM - The SSL network communication service 'SslConnector' is missing the trustStor file (/config/ssl/certificates.jks)
09:45:47.920 [Main] WARN  LINSTOR/Controller - SYSTEM - NetComService: Connector SslConnector: Binding the socket to the IPv6 anylocal address failed, attempting fallback to IPv4
09:45:47.924 [Main] INFO  LINSTOR/Controller - SYSTEM - Created network communication service 'SslConnector', bound to ::0:3377
09:45:47.926 [Main] INFO  LINSTOR/Controller - SYSTEM - Reconnecting to previously known nodes
09:45:48.424 [Main] INFO  LINSTOR/Controller - SYSTEM - Reconnect requests sent
May 29, 2020 9:45:51 AM org.glassfish.grizzly.http.server.accesslog.FileAppender <init>
INFO: Access log file "/logs/rest-access.log" opened
May 29, 2020 9:45:51 AM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [127.0.0.1:3370]
May 29, 2020 9:45:51 AM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
09:45:51.383 [Main] INFO  LINSTOR/Controller - SYSTEM - Controller initialized
09:45:53.886 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.130.166:3366 has closed the connection.
09:45:53.902 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.129.111:3366 has closed the connection.
09:45:53.924 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.130.201:3366 has closed the connection.
09:45:53.948 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.129.174:3366 has closed the connection.
09:45:53.955 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.128.215:3366 has closed the connection.
09:45:53.984 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.131.2:3366 has closed the connection.
09:45:54.001 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.129.205:3366 has closed the connection.
09:45:54.020 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.130.162:3366 has closed the connection.
09:46:06.143 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.129.163:3366 has closed the connection.
09:46:06.166 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.130.212:3366 has closed the connection.
09:46:06.169 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.129.123:3366 has closed the connection.
09:46:06.180 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.130.62:3366 has closed the connection.
09:46:06.204 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.130.73:3366 has closed the connection.
09:46:06.207 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.129.24:3366 has closed the connection.
09:46:06.214 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.130.254:3366 has closed the connection.
09:46:06.327 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.130.175:3366 has closed the connection.
09:46:06.332 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.129.218:3366 has closed the connection.
09:46:06.365 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.129.58:3366 has closed the connection.
09:46:06.387 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.130.159:3366 has closed the connection.
09:46:06.401 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.130.50:3366 has closed the connection.
09:46:10.072 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.129.147:3366 has closed the connection.
09:46:10.793 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.131.14:3366 has closed the connection.
09:46:14.963 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.130.84:3366 has closed the connection.
09:46:16.796 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.128.222:3366 has closed the connection.
09:46:26.297 [PlainConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /10.36.129.172:3366 has closed the connection.
```

**Comment by kvaps** [comment]
Hi, the same problem persist on v1.7.2 (debian bullseye)

**Comment by rp-** [comment]
I tried to reproduce the deadlock, but still with a fairly small cluster(20 nodes with SSL) compared to your 550 and couldn't once reproduce any deadlock.

I'm afraid to progress here we will need you to start the controller with a debug port and once you hit the deadlock, connect with a debugger and give as the full stacktrace of all threads.
If you need help on how to set this up, I can write something up

**Comment by kvaps** [comment]
@rp- sure, I can do that.
I will do that on production cluster, so please correct me if I something miss:

- I need to run `/usr/share/linstor-server/bin/Controller` with `--debug-console` flag
- Then reproduce the deadlock situation
- Then collect the output of `DspThr` command?

**Comment by rp-** [comment]
Not exactly, a bit more low level.

* You have to start the jvm with a debug port. e.g.
Care default system controller options are missing `-c -l`....
`CONTROLLER_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n" /usr/share/linstor-server/bin/Controller`
* and the reproduce the deadlock
* connect with `jdb -attach 8000`
* run `suspend`
* and `where all`
* and paste the output of that

**Comment by kvaps** [comment]
OK, I prepared four captures:

1. I reconfigured satellites to use SSL, then restarted controller with debug port, and I've got first deadlock:

    * [1-threads.txt](https://github.com/LINBIT/linstor-server/files/4934876/1-threads.txt)

2. Then I killed controller with `-9` and after starting up, I started reconfiguring nodes to use SSL:

    ```bash
    linstor n l | awk '/(PLAIN)/ { print "linstor n i m -p 3367 --communication-type SSL " $2 " default" }' | sh -ex
    ```

    All nodes were reconfigured successfully, but only one first quoter were online, the reset were report the connection error, despite the fact satellites were reachable and accessible via telnet.

    * [ErrorReport-5F10D854-00000-000466.log](https://github.com/LINBIT/linstor-server/files/4934887/ErrorReport-5F10D854-00000-000466.log)
    * [ErrorReport-5F10D854-00000-000321.log](https://github.com/LINBIT/linstor-server/files/4934888/ErrorReport-5F10D854-00000-000321.log)

    So I rebooted controller again.

    After reboot it started trying to establish connection with the nodes they were changing their state like: `OFFLINE` --> `Connecting` --> `Online`, and when almost all of them were Online, the deadlock happened:

    * [2-threads.txt](https://github.com/LINBIT/linstor-server/files/4934878/2-threads.txt)

3. `kill -9` than start controller again, go deadlock with same behavior:

    * [3-threads.txt](https://github.com/LINBIT/linstor-server/files/4934879/3-threads.txt)

4. `kill -9` than start controller again, go deadlock with same behavior:

    * [4-threads.txt](https://github.com/LINBIT/linstor-server/files/4934881/4-threads.txt)

5. `kill -9` than start controller again with TRACE log, go deadlock with same behavior:

    * [5-threads.txt](https://github.com/LINBIT/linstor-server/files/4934882/5-threads.txt)

6. `kill -9` than start controller again with TRACE log, go deadlock with same behavior:

    * [6-threads.txt](https://github.com/LINBIT/linstor-server/files/4934883/6-threads.txt)

After that I restarted services and reconfigured to use plain connection, since that no deadlocks anymore.

I think this happens when controller losing the connection with some nodes, I usually see something like that in the log:
```
[TaskScheduleService] TRACE LINSTOR/Controller - SYSTEM - Connection to Node: 'm12c32' lost. Removed from pingList, added to reconnectList.
[TaskScheduleService] TRACE LINSTOR/Controller - SYSTEM - Event 'connection closed' start: Node: 'm12c32'
[TaskScheduleService] TRACE LINSTOR/Controller - SYSTEM - Event 'connection closed' end: Node: 'm12c32'
```.
Or it might be connected with huge amount of requests to list the nodes and storage pools on them.

**Comment by rp-** [comment]
Thanks to your stacktraces I could find the deadlock quite easily!
They all point to the same deadlock (wrong locking order).

I attached a server-1.7.2.jar you can put in /usr/share/linstor-server/lib with a fix for the deadlock and test.
(I had to gzip it, for github to allow upload)

[server-1.7.2.jar.gz](https://github.com/LINBIT/linstor-server/files/4936228/server-1.7.2.jar.gz)

**Comment by kvaps** [comment]
Thanks! I'll check this during the night.

**Comment by kvaps** [comment]
```
Version:            1.7.2 (7cdf6b63ece868897519e2268ca7c2daac09de44)
Build time:         2020-07-17T06:30:51+00:00
```
Ok, it seems deadlock is still there:

1. I switched satellites to use SSL configuration, and restarted controller, immediately got the first deadlock.

2. `kill -9`, then start controller, then attempt to reconfigure nodes, got deadlock of fifth node.

3.  `kill -9`, install debugger then start controller with debug port, attempt to reconfigure nodes, got deadlock of on one half reconfigured:

    * [3-threads.txt](https://github.com/LINBIT/linstor-server/files/4940870/3-threads.txt)

4.  `kill -9`, start controller with debug port, deadlock after initialization

    * [4-threads.txt](https://github.com/LINBIT/linstor-server/files/4940871/4-threads.txt)

5.  `kill -9`, start controller with debug port, deadlock after initialization

    * [5-threads.txt](https://github.com/LINBIT/linstor-server/files/4940872/5-threads.txt)

**Comment by rp-** [comment]
:/
ok sorry, looks like I was a bit too naive with my approach.

I'll have a look with Gabor on it on Monday and come back to you.

**Comment by kvaps** [comment]
Ok, I can append that I can get into this situation when satellite nodes are online.
I think that some operations like querying the size of LVM-pools might cause this.
First `linstor n l` is stopping working. Then the rest commands, eg. `linstor c v`

**Comment by rp-** [comment]
Here is a new version for you to try.
This time I could reproduce the deadlock with some tricks, so this fix is somewhat tested.

[server-1.7.2.jar.gz](https://github.com/LINBIT/linstor-server/files/4946264/server-1.7.2.jar.gz)

**Comment by kvaps** [comment]
Thanks, but I wasn't able to run it on staging environment.
The version number has been changed, so I have version conflict even after replacing server-1.7.2.jar on satellites.

Another question: is it safe to run `1.7.1.78-a28ae9e71` on top of `1.7.2`?

**Comment by rp-** [comment]
Sorry, I don't know how this happend, I built it the same way as on friday.
So here is another try(checked the version in the file)
No it will not work if semantic version number do not match (VERSION_MISMATCH)

[server-1.7.2.jar.gz](https://github.com/LINBIT/linstor-server/files/4946744/server-1.7.2.jar.gz)

**Comment by kvaps** [comment]
Ok, should I upgrade only controller or satellites too?

**Comment by rp-** [comment]
controller should be enough

**Comment by kvaps** [comment]
Ok staging is up and running, I'll try production cluster tonight

**Comment by kvaps** [comment]
The weird thing which I found on staging is that now linstor-controller can not handle all the connections, eg some nodes loses their connection and swap to `OFFLINE` state:

```
╭───────────────────────────────────────────────────────╮
┊ Node  ┊ NodeType  ┊ Addresses               ┊ State   ┊
╞═══════════════════════════════════════════════════════╡
┊ m1c4  ┊ SATELLITE ┊ 10.28.36.164:3367 (SSL) ┊ OFFLINE ┊
┊ m1c5  ┊ SATELLITE ┊ 10.28.36.165:3367 (SSL) ┊ OFFLINE ┊
┊ m1c6  ┊ SATELLITE ┊ 10.28.36.166:3367 (SSL) ┊ Online  ┊
┊ m1c7  ┊ SATELLITE ┊ 10.28.36.167:3367 (SSL) ┊ Online  ┊
┊ m1c8  ┊ SATELLITE ┊ 10.28.36.168:3367 (SSL) ┊ Online  ┊
┊ m1c9  ┊ SATELLITE ┊ 10.28.36.169:3367 (SSL) ┊ OFFLINE ┊
┊ m1c10 ┊ SATELLITE ┊ 10.28.36.170:3367 (SSL) ┊ Online  ┊
┊ m1c12 ┊ SATELLITE ┊ 10.28.36.172:3367 (SSL) ┊ Online  ┊
┊ pve1  ┊ SATELLITE ┊ 10.28.36.159:3367 (SSL) ┊ OFFLINE ┊
┊ pve2  ┊ SATELLITE ┊ 10.28.36.160:3367 (SSL) ┊ Online  ┊
┊ pve3  ┊ SATELLITE ┊ 10.28.36.161:3367 (SSL) ┊ Online  ┊
╰───────────────────────────────────────────────────────╯
```

**Comment by rp-** [comment]
you mean, they alter their connection state all the time?
or are they all online after some time?

**Comment by kvaps** [comment]
After the boot they are changing their state like:

`OFFLINE` --> `Connected` --> `OFFLINE` and usually stay offline

Unfortunately I wasn't able to reproduce this right now.
Well, our staging cluster is a bit overheated and throttling the CPUs, I guess it might be related.

Controller logs are clean, satelites shows the few connection attempts from the controller:
```
12:25:15.578 [MainWorkerPool-1] INFO  LINSTOR/Satellite - SYSTEM - Controller connected and authenticated (10.112.1.63:52506)
```

and many-many resources created afterwards:
```
...
12:25:20.145 [MainWorkerPool-1] INFO  LINSTOR/Satellite - SYSTEM - Resource 'one-image-116' created for node 'm1c4'.
12:25:20.145 [MainWorkerPool-1] INFO  LINSTOR/Satellite - SYSTEM - Resource 'one-image-116' created for node 'm1c6'.
12:25:20.148 [MainWorkerPool-1] INFO  LINSTOR/Satellite - SYSTEM - Resource 'one-image-119' created for node 'm1c4'.
...
```

**Comment by rp-** [comment]
maybe the node times out while doing the initial sync, because of the many node requests.

**Comment by kvaps** [comment]
Maybe these nodes are having about 200 resources assigned.
For now it's working, so let's see how it will work on production cluster.

**Comment by kvaps** [comment]
Ok, now it seems bug is fixed, good job!
Thanks a lot!

Separately I can notice that node connection process is now longer than with plain connector.
Usually I'm waiting about 1m30s before I get `Controller initialized` message and after 20 more seconds cluster becomes to operable state.

For now I was forced to wait about 2-3 minutes while all my nodes were blinking between `Online` and `OFFLINE` and after that all of them switched their state to green.
