### ISSUE TITLE
Feature Request: lvcreate with stripes option

### ISSUE THREAD

**Issue by ddpolyakov** [LINBIT/linstor-server#149]
I didn't find any option where I can set stripe value in case of using thick LVM. 
Striping maybe useful in many cases: capacity balancing on vg, paralleling performance etc.

**Comment by ghernadi** [comment]
Sorry - I forgot to update the documentation. 

You are looking for 
```
linstor storage-pool set-property $node_name $storage_pool_name StorDriver/LvcreateType striped
```

Other values can be found here
https://app.swaggerhub.com/apis-docs/Linstor/Linstor/1.1.0#/developers/nodeStoragePoolModify

That value will be simply appended to Linstor's `lvcreate ... --type=`, whereas `linear` is the default

For some reason you cannot set that property on node or controller level. I will fix that in the next version.  
I will also update the users-guide (after I figured out where a good place would be adding this piece of information)

**Comment by ddpolyakov** [comment]
Nice. Thanks a lot. Worked out great for me.

**Comment by maxpain** [comment]
> Sorry - I forgot to update the documentation.
> 
> You are looking for
> 
> ```
> linstor storage-pool set-property $node_name $storage_pool_name StorDriver/LvcreateType striped
> ```
> 
> Other values can be found here https://app.swaggerhub.com/apis-docs/Linstor/Linstor/1.1.0#/developers/nodeStoragePoolModify
> 
> That value will be simply appended to Linstor's `lvcreate ... --type=`, whereas `linear` is the default
> 
> For some reason you cannot set that property on node or controller level. I will fix that in the next version. I will also update the users-guide (after I figured out where a good place would be adding this piece of information)

@ghernadi 

I tried this:
```bash
linstor storage-pool set-property w1 nvme-lvm StorDriver/LvcreateType striped
```

![telegram-cloud-photo-size-2-5190904956234884549-y](https://github.com/user-attachments/assets/46575088-0c8a-45da-bbd7-646e3a8b7881)

But new volumes are still linear

![telegram-cloud-photo-size-2-5190904956234884552-y](https://github.com/user-attachments/assets/c857f946-fa4a-445e-87f9-2e70b4481377)

I use piraeus-operator

**Comment by maxpain** [comment]
I've managed to enable LVM striping:

```bash
linstor  storage-pool set-property  $host ssd-lvm StorDriver/LvcreateOptions ' -i 2'
```
