### ISSUE TITLE
LINSTOR Stork scheduling on TieBreaker

### ISSUE THREAD

**Issue by fondemen** [LINBIT/linstor-server#157]
Hello !

I can't send an issue on the [LINBIT/stork](https://github.com/LINBIT/stork) so I post it here...

I'm trying to use Linstor on Kubernetes with Stork scheduler so that my pods are co-located with their linstor-provisionned volumes. Each volume is configured to have 2 replicas, and as such, two nodes are selected by Linstor for a replica, and another one for an arbiter (TieBreaker). As far as I understand, the latter node does not hold ay data for the volume. 

But it seems that pods are scheduled by the Stork scheduler (equipped with Linstor driver) on TieBreaker nodes, which looks strange to me as data remains remote to the pod. If I disable TieBreaker, nodes are indeed properly scheduled on one of the data nodes.

Is there any mean to prevent scheduling on TieBreakers nodes?

See kvaps/kube-linstor#13 for the complete investigation history.

**Comment by chrboe** [comment]
Thanks for the report! We had actually fixed this internally a short while ago, I just haven't published an image yet.

I'll publish the fix today.

**Comment by chrboe** [comment]
Done: https://github.com/LINBIT/stork/commit/142f1cce632707aafc8b8df326e45f392687ffb6

(Also published on Dockerhub)

**Comment by fondemen** [comment]
Thanks a lot !
