### ISSUE TITLE
Stuck operations and controller dead after restarting linstor-satellite

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#16]
Today was interesting issue,
Linstor was creating new resources but wasn't update their config on one node.
After restarting `linstor-satellite` on this node, `linstor-controller` was dead:
```
Controller[3868]: 16:16:35.219 [PlainConnector] INFO  LINSTOR/Controller - Remote satellite peer /10.28.36.161:3366 has closed the connection.
Controller[3868]: 16:16:35.220 [PlainConnector] ERROR LINSTOR/Controller - Problem of type 'java.util.ConcurrentModificationException' logged to report number 5BA284EF-00000-012789
```

```
ERROR REPORT 5BA284EF-00000-012789

============================================================

Application:                        LINBIT? LINSTOR
Module:                             Controller
Version:                            0.6.4
Build ID:                           464f6e5b198002e0d82122d84c27e1b06ec0400c
Build time:                         2018-09-14T09:11:03+00:00
Error time:                         2018-10-01 16:16:35
Node:                               linstor-controller

============================================================

Reported error:
===============

Category:                           RuntimeException
Class name:                         ConcurrentModificationException
Class canonical name:               java.util.ConcurrentModificationException
Generated at:                       Method 'nextEntry', Source file 'TreeMap.java', Line #1211


Call backtrace:

    Method                                   Native Class:Line number
    nextEntry                                N      java.util.TreeMap$PrivateEntryIterator:1211
    next                                     N      java.util.TreeMap$ValueIterator:1256
    connectionClosing                        N      com.linbit.linstor.netcom.TcpConnectorPeer:454
    closeConnection                          N      com.linbit.linstor.netcom.TcpConnectorService:966
    closeConnection                          N      com.linbit.linstor.netcom.TcpConnectorService:955
    run                                      N      com.linbit.linstor.netcom.TcpConnectorService:532
    run                                      N      java.lang.Thread:748


END OF ERROR REPORT.
```

After restarting `linstor-controller` too, it was started working as it should.

**Comment by ghernadi** [comment]
The error regarding the `ConcurrentModificationException` (your posted ErrorReport) is already fixed and will be included in the next release (should come in the next few days)

I am more curious about what happened at the satellite that it didn't update its resource files? Is there any interesting ErrorReport or other indication from that issue?

**Comment by raltnoeder** [comment]
Should already be fixed for the next release, commit `c175c5572afc46cf3ee88c9e1cd8c362b2b5af30`.

**Comment by kvaps** [comment]
> The error regarding the `ConcurrentModificationException` (your posted ErrorReport) is already fixed and will be included in the next release (should come in the next few days)
> 
> I am more curious about what happened at the satellite that it didn't update its resource files? Is there any interesting ErrorReport or other indication from that issue?

Unfortunately I have no more information for you, I'll let you know if problem will occurs again.
Thanks!

**Comment by ghernadi** [comment]
If it occurs again, and still no ErrorReport is produced, it would help if you could tell what you did, maybe we can reconstruct the error with such a description
