### ISSUE TITLE
feature request: limit number of active resync jobs

### ISSUE THREAD

**Issue by ggzengel** [LINBIT/linstor-server#163]
Multiple disk access reduce significant the resyncing speed and slows down the boot up of VMs.
It would be much better to configure the number of active resync jobs per storage pool.

**Comment by raltnoeder** [comment]
Resync is controlled by DRBD, which has no notion of storage pools. DRBD supports global resync priorities (resync this volume first, only afterwards resync that other volume, etc.), but not per storage pool.

**Comment by ggzengel** [comment]
So, is it possible if no priority given to limit the max number of resync jobs?

**Comment by rp-** [comment]
No you can only set the drbd-option resync-after and create a chain of resource to sync.
But AFIAK DRBD tries to resync in such rates, that it doesn't affect application writes too much.
But anyway this is more a issue for DRBD
