### ISSUE TITLE
A DRDB-resource cannot be activated again!

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#164]
```bash
# linstor r l -r test1
╭─────────────────────────────────────────────────────────────────────╮
┊ ResourceName ┊ Node  ┊ Port ┊ Usage  ┊ Conns ┊    State ┊ CreatedOn ┊
╞═════════════════════════════════════════════════════════════════════╡
┊ test1        ┊ m1c12 ┊ 7331 ┊ Unused ┊ Ok    ┊ UpToDate ┊           ┊
╰─────────────────────────────────────────────────────────────────────╯
```

```bash
# linstor r deactivate m1c12 test1
SUCCESS:
    Resource deactivated on 'm1c12'

# linstor r activate m1c12 test1
ERROR:
Description:
    A DRDB-resource cannot be activated again!
Details:
    Node: m1c12, Resource: test1
Show reports:
    linstor error-reports show 5F311159-00000-000002
```

```bash
# linstor r l -r test1
╭───────────────────────────────────────────────────────────────────╮
┊ ResourceName ┊ Node  ┊ Port ┊ Usage ┊ Conns ┊   State ┊ CreatedOn ┊
╞═══════════════════════════════════════════════════════════════════╡
┊ test1        ┊ m1c12 ┊ 7331 ┊       ┊       ┊ Unknown ┊           ┊
╰───────────────────────────────────────────────────────────────────╯
```

[5F311159-00000-000002.log](https://github.com/LINBIT/linstor-server/files/5049951/5F311159-00000-000002.log)

**Comment by ghernadi** [comment]
Hmm.. seems like I missed a warning when deactivating a resource that you will not be able to activate it again... 

The "error" here is [intentional](https://www.linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-shipping_snapshots-linstor) (actually we should also skip generating the ErrorReport for it). 

The reason for this is that during snapshot-shipping (which requires the target resource to be deactivated) will receive also the metadata from the sender. Activating the resource in this state will definitely break.   
As the docs also mentions, you can still restore the snapshot into a new resource(-definition) which will regenerate all meta-data of all those new resources.

**Comment by kvaps** [comment]
Hi @ghernadi,

Thanks for explanation, I just thinking that `activate`/`deactivate` is not fully suitable terminoloy for this

I saw new ```deactivate / activate``` options for the linstor CLI and immediately made a decision that it is the same like:
```drbdadm down / drbdadm up``` or ```drbdadm disconnect / drbdadm connect```, something that can be reverted afterwards.

Actually that's my fault that I'm not reading the documentation before trying new features, but I'm sure that there will be another people with the same problem :)

Besides I think it's better to reserve these terminology for the ```drbdadm down / drbdadm up``` if this functional will apears in linstor sometime.

disclaimer: I do not requesting anything from you, that's just my thoughts on this :)

**Comment by kvaps** [comment]
I also bit confused that deactivated resource is shown as `Unknown`, I think it's better to rename it to something like `SnapTarget`  or etc.

```
# linstor r l -r one-image-32
╭───────────────────────────────────────────────────────────────────────────────╮
┊ ResourceName ┊ Node  ┊ Port ┊ Usage  ┊ Conns ┊    State ┊ CreatedOn           ┊
╞═══════════════════════════════════════════════════════════════════════════════╡
┊ one-image-32 ┊ m1c10 ┊ 7097 ┊ Unused ┊ Ok    ┊ UpToDate ┊                     ┊
┊ one-image-32 ┊ m1c12 ┊ 7097 ┊        ┊       ┊  Unknown ┊ 2020-08-10 14:15:27 ┊
┊ one-image-32 ┊ m1c6  ┊ 7097 ┊ Unused ┊ Ok    ┊ UpToDate ┊                     ┊
╰───────────────────────────────────────────────────────────────────────────────╯
```

**Comment by kvaps** [comment]
@ghernadi could you please clarify why `linstor resource activate` command is needed for if

> Deactivating a resource with DRBD in its layer-list can NOT be reactivated again.

**Comment by kvaps** [comment]
My theory was correct, creating resource without DRBD layer allows to deactivate and activate.

```bash
# linstor  r c m1c4 one-image-50 -l STORAGE -s thindata
SUCCESS:
    Successfully set property key(s): StorPoolName
SUCCESS:
Description:
    New resource 'one-image-50' on node 'm1c4' registered.
Details:
    Resource 'one-image-50' on node 'm1c4' UUID is: 58f627f1-e84d-4e9a-954c-a4297f9c281f
SUCCESS:
Description:
    Volume with number '0' on resource 'one-image-50' on node 'm1c4' successfully registered
Details:
    Volume UUID is: a3b555e3-09e0-4c57-8db4-846fe9592edb
SUCCESS:
    Added peer(s) 'm1c4' to resource 'one-image-50' on 'm1c6'
SUCCESS:
    Added peer(s) 'm1c4' to resource 'one-image-50' on 'm1c5'
SUCCESS:
    Created resource 'one-image-50' on 'm1c4'
```

```bash
# linstor r l -r one-image-50
╭──────────────────────────────────────────────────────────────────────────────╮
┊ ResourceName ┊ Node ┊ Port ┊ Usage  ┊ Conns ┊    State ┊ CreatedOn           ┊
╞══════════════════════════════════════════════════════════════════════════════╡
┊ one-image-50 ┊ m1c4 ┊ 7116 ┊        ┊       ┊  Unknown ┊ 2020-08-11 08:20:50 ┊
┊ one-image-50 ┊ m1c5 ┊ 7116 ┊ Unused ┊ Ok    ┊ UpToDate ┊                     ┊
┊ one-image-50 ┊ m1c6 ┊ 7116 ┊ Unused ┊ Ok    ┊ UpToDate ┊                     ┊
╰──────────────────────────────────────────────────────────────────────────────╯
```

```bash
# linstor r deactivate m1c4 one-image-50
SUCCESS:
    Resource marked inactivate on 'm1c5'
SUCCESS:
    Resource marked inactivate on 'm1c6'
SUCCESS:
    Resource deactivated on 'm1c4'
```

```bash
# linstor r deactivate m1c4 one-image-50
INFO:
    Resource is already deactivated. Noop
root@linstor-controller-0:/# linstor r activate m1c4 one-image-50
SUCCESS:
    Reactivating resource on 'm1c5'
SUCCESS:
    Reactivating resource on 'm1c6'
SUCCESS:
    Reactivating resource on 'm1c4'
SUCCESS:
    Resource activated on 'm1c6'
SUCCESS:
    Resource activated on 'm1c4'
SUCCESS:
    Resource activated on 'm1c5'
```

But this is working only with the new resources which weren't shipped previously

**Comment by ghernadi** [comment]
As also mentioned in the [other comment](https://github.com/LINBIT/linstor-server/issues/169#issuecomment-671834860), for now I think that Linstor should not allow mixing layer-lists... I will have a look into this for more details.

> But this is working only with the new resources which weren't shipped previously

Not exactly. (re-) activating is only allowed in this case because Linstor does not find DRBD in the resource's layer-list. This is actually only useful for non-DRBD resources.
