### ISSUE TITLE
Authorization for /health

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#165]
Hi, last release `v1.7.0` was providing `/health` without authorization.

```bash
curl 'http://localhost:3370/health'
```

But `v1.8.0-rc1` now requires an authorization:

```bash
# curl 'http://localhost:3370/health'
<html>
<head><title>Document moved</title></head>
<body><h1>Document moved</h1>
This document has moved <a href="https://localhost:3371/health">here</a>.<p>
</body>
</html>
```

```bash
# curl -k https://localhost:3371/health
curl: (52) Empty reply from server
```

The only way to check the health now is to provide proper client certificate for that:
```
curl --cacert /tls/ca.crt --cert /tls/tls.crt --key /tls/tls.key 'https://localhost:3371/health'
```

I'm not sure if this is expected change or regression, but this change makes [HTTP probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes) non working in Kubernetes anymore

maybe, it's make sense for make it available on HTTPS but without authentication:

> If scheme field is set to HTTPS, the kubelet sends an HTTPS request skipping the certificate verification.

**Comment by rp-** [comment]
This is definitly a regression, I'll have a look at it

**Comment by rp-** [comment]
`/health` url should now always work
