### ISSUE TITLE
"journalctl": error=2, No such file or directory

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#167]
Hi, we're using linstor in a containers, executing this command returns error:
```bash
# linstor sos-report create
ERROR:
    Cannot run program "journalctl": error=2, No such file or directory
Show reports:
    linstor error-reports show 5F312590-00000-000003
```

[5F312590-00000-000003.log](https://github.com/LINBIT/linstor-server/files/5050445/5F312590-00000-000003.log)

**Comment by rp-** [comment]
should be fixed in final 1.8.0
