### ISSUE TITLE
FeatureRequest: Zones

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#17]
Hi, I want to have opportunity for placing resources per zones eg., I have two chassis per 45 cartridges.
And I need to autoplace resource to both of them.

**Comment by haySwim** [comment]
You can use differently named storage pools as a way to create zones. Autoplace only considers nodes that have the requested storage pool present on them.

**Comment by kvaps** [comment]
Hey, that's true, so should run my placing command twice? For zone1 and for zone2?

```
linstor r c test --auto-place 1 -s zone1
linstor r c test --auto-place 2 -s zone1
```
Is that true way?

**Comment by ghernadi** [comment]
Your example contains the same storage pool twice. In case you write `zone2` for one of the commands, that should work, yes.

Anyways, you could take a look into `--replicas-on-different AUX_NODE_PROPERTY [AUX_NODE_PROPERTY ...]` option. For that you will have to store aux-properties on all nodes which you want to reference once. For example:

```
linstor n sp <node_name>       --aux myCategory A
...
linstor n sp <other_node_name> --aux myCategory B
```
and then a single --auto-place:
```
linstor r c <resource_name> --auto-place 2 --replicas-on-different myCategory
```
I hope I am not confusing "myCategory" with "aux/mycategory" at the last call.

**Comment by kvaps** [comment]
> Your example contains the same storage pool twice. In case you write `zone2` for one of the commands, that should work, yes.
> 
> Anyways, you could take a look into `--replicas-on-different AUX_NODE_PROPERTY [AUX_NODE_PROPERTY ...]` option. For that you will have to store aux-properties on all nodes which you want to reference once. For example:
> 
> ```
> linstor n sp <node_name>       --aux myCategory A
> ...
> linstor n sp <other_node_name> --aux myCategory B
> ```
> 
> and then a single --auto-place:
> 
> ```
> linstor r c <resource_name> --auto-place 2 --replicas-on-different myCategory
> ```
> 
> I hope I am not confusing "myCategory" with "aux/mycategory" at the last call.

That's what exactly I needed, thanks!
