### ISSUE TITLE
feature request: backup and restore database

### ISSUE THREAD

**Issue by ggzengel** [LINBIT/linstor-server#178]
1. I will backup the database with cron
2. I will migrate to etcd and multiple controllers because I don't like the Promox/LinStor HA solution

**Comment by ghernadi** [comment]
Not sure if I understand you correctly. Anything we can help you here?

**Comment by ggzengel** [comment]
Sorry, this should be a feature request to store the linstor database independent from the database engine with the option to restore the database to an other database engine.

**Comment by ggzengel** [comment]
In the first step it would be enough to backup the h2 database (`linstor backup /tmp/backup.sql`), because it's not possible to backup from outside without shutdown of linstor-controller: https://www.tutorialspoint.com/h2_database/h2_database_backup.htm

**Comment by rp-** [comment]
this seems to be related to: https://github.com/LINBIT/linstor-server/issues/31

But I'm also pretty sure you can just copy away the h2 database file to another location, it should always be consistent.

**Comment by rp-** [comment]
In one of the latest release, linstor learned to "correctly" backup the h2 DB, which can be trigger by a REST request:
https://app.swaggerhub.com/apis-docs/Linstor/Linstor/1.13.0#/developers/controllerBackupDB

**Comment by ggzengel** [comment]
If somebody finds this thread, there is now linstore-database for import/export:
[controller/src/main/java/com/linbit/linstor/core/LinstorDatabaseTool.java](https://github.com/LINBIT/linstor-server/blob/master/controller/src/main/java/com/linbit/linstor/core/LinstorDatabaseTool.java)
