### ISSUE TITLE
Failure while trying to create a resource when one node is down

### ISSUE THREAD

**Issue by chiraganand** [LINBIT/linstor-server#180]
```
$ linstor n l
╭────────────────────────────────────────────────────────────────╮
┊ Node        ┊ NodeType  ┊ Addresses                  ┊ State   ┊
╞════════════════════════════════════════════════════════════════╡
┊ drbd-node1  ┊ SATELLITE ┊ 172.16.23.236:3366 (PLAIN) ┊ Online  ┊
┊ drbd-node2  ┊ SATELLITE ┊ 172.16.23.238:3366 (PLAIN) ┊ Online  ┊
┊ drbd-node3  ┊ SATELLITE ┊ 172.16.23.241:3366 (PLAIN) ┊ OFFLINE ┊
┊ XXX         ┊ SATELLITE ┊ 172.16.22.117:3366 (PLAIN) ┊ Online  ┊
╰────────────────────────────────────────────────────────────────╯
```

```
$ linstor r c --auto-place 2 test1
ERROR:
Description:
    Satellite 'drbd-node3' does not support the following layers: [DRBD]
Details:
    Auto-placing resource: test1
Show reports:
    linstor error-reports show 5F46591B-00000-000009
```

[ErrorReport-5F46591B-00000-000009.log](https://github.com/LINBIT/linstor-server/files/5135807/ErrorReport-5F46591B-00000-000009.log)

_Originally posted by @chiraganand in https://github.com/LINBIT/linstor-server/issues/173#issuecomment-681865730_

## Steps to reproduce

1. Create 3 Linstor/DRBD nodes.
2. Create resource definitions and volume defs which will get created without a problem.
3. On one of the nodes switch off satellite: `systemctl stop linstor-satellite.service`
4. Check Linstor node is offline with `linstor node list`
5. Create a new resource definition: `linstor rd c test`
6. Create volume definition: `linstor vd c test 1G`. This operation doesn't fail or throw any error but also doesn't create the resource.
7. Creating the resource manually throws an exception: `linstor resource create --auto-place 2 test`

**Comment by rp-** [comment]
just tested and this works now
