### ISSUE TITLE
Feature request: Add prefix as an option of db_etcd configuration 

### ISSUE THREAD

**Issue by ddpolyakov** [LINBIT/linstor-server#182]
As far as I can see - it is hardcoded prefix "LINSTOR"  for etcd db connection inside etcd driver in Linstor-controller. In that case Im unable to use one etcd cluster for multiple linstor clusters. It would be nice to have a configurable option for Linstor-controller to use different prefixes.

**Comment by ghernadi** [comment]
Out of curiosity - can you tell me why you want to have multiple Linstor clusters?

**Comment by ddpolyakov** [comment]
> Out of curiosity - can you tell me why you want to have multiple Linstor clusters?

In my particular case - to create multiple stages/dev environments that are using one k8s with one etcd.

**Comment by rck** [comment]
Just as a hint, you would then need to be careful to not create colliding block device minor numbers (e.g., two drbd1000), but I'm sure there is some  config value for that in LINSTOR. Maybe there are some MIN (and even MAX) values.

**Comment by rp-** [comment]
see v1.10.0
