### ISSUE TITLE
Etcd Initial load from the database failed

### ISSUE THREAD

**Issue by ddpolyakov** [LINBIT/linstor-server#183]
I had mistake of database inititalization after I made renumbering on a few satellites. 
I made a renumbering via `linstor n i m --ip `dig +short $(hostname)` $(hostname) default ` and had a right output in `linstor n l` after. But when I restarted my controller next time I had an _Failed to restore data_ error message. After an investigation I found out that all nodes Ive been renumbering - had a etcd records in INET_ADDRESS like _com.linbit.linstor.core.types.LsIpAddress@156a3381_, for example:
_/LINSTOR/NODE_NET_INTERFACES/NODE.DOMAIN:DEFAULT/INET_ADDRESS
com.linbit.linstor.core.types.LsIpAddress@156a3381_ instead of _/LINSTOR/NODE_NET_INTERFACES/KBT-NODE2.DOMAIN:DEFAULT/INET_ADDRESS
10.0.0.0_
that what I exactly had in linstor ErrorReport

> Category:                           Exception
> Class name:                         InvalidIpAddressException
> Class canonical name:               com.linbit.InvalidIpAddressException
> Generated at:                       Method '<init>', Source file 'LsIpAddress.java', Line #26
> 
> Error message:                      com.linbit.linstor.core.types.LsIpAddress@1ef207b2
>

**Comment by ddpolyakov** [comment]
Im using linstor controller 1.7.1 and etcd 3.2.24

**Comment by rp-** [comment]
Thanks for the report, will be fixed in the next release
