### ISSUE TITLE
Commands like "linstor v l" are very slow or time out. We have many outdated resources too.

### ISSUE THREAD

**Issue by tobg** [LINBIT/linstor-server#185]
Hello,

we are using linstor on kubernetes 1.18.6. Everything worked fin until a volume got disconnected from one of our six nodes.
Now we have many outdated resources and commands like linstor v l or linstor r l are very slow or time out.

What can we do to resolve this? Thank you.

**Comment by rp-** [comment]
I guess first thing to try would be restarting the satellites and see if they can reconnect the resources.
If there is still a problem there must be some connection or drbd problem why they can't.
I'm not very familiar with k8s setups, so I can only help with plain linstor issues

**Comment by ghernadi** [comment]
Also - what do you mean with 

> volume got disconnected from one of our six nodes.

Even if `linstor v l` is slow, if it does not timeout, what does the output look like? Anything suspicious?
Also what about `linstor n l` or `linstor sp l`?

**Comment by tobg** [comment]
Thanks guys, I had to restart everything and now it looks far better. One Ressource will not synchronize completely. It always get to 99.97% and stuck there.  SyncTarget(99.97%)

What can I do herer? I already tried disconnect and connect with --discard-my-data=yes

**Comment by ghernadi** [comment]
Try upgrading DRBD. A bug was fixed in the last few versions that could cause such behavior.

**Comment by tobg** [comment]
Thanks. Already did this. Transports (api:16): tcp (9.0.25-1) This is the used version now

**Comment by rp-** [comment]
Than you can only check the `dmesg` log on the involved machines for hints in the drbd log and forward that to the drbd team.

**Comment by tobg** [comment]
I did a complete reinstall and now it works fast.

**Comment by tobg** [comment]
I did a complete reinstall and now it works fast.
