### ISSUE TITLE
Handlers outdate-peer missing

### ISSUE THREAD

**Issue by jvinolas** [LINBIT/linstor-server#192]
Hi,

I'm trying to set up a linstor drbd with a gfs2 active/active cluster filesystem on top, within a pacemaker cluster. As said in the drbd9 documentation it should be set up with net fence resource-and-stonith (which is defined) and also with the handlers outdate-peer "/sbin/kill-other-node.sh" (which I don't see defined https://github.com/LINBIT/linstor-server/blob/master/docs/rest_v1_openapi.yaml)

> root@cluster1:/opt/setup/pacemaker# linstor controller set-property DrbdOptions/Net/fencing resource-and-stonith
SUCCESS:
    Successfully set property 'DrbdOptions/Net/fencing' to value 'resource-and-stonith'
root@cluster1:/opt/setup/pacemaker# linstor controller set-property DrbdOptions/Handlers/outdate-peer "/sbin/kill-other-node.sh"
ERROR:
    The key 'DrbdOptions/Handlers/outdate-peer' is not whitelisted

And in the documentation it says:

>  All cluster file systems require fencing – not only via the DRBD resource, but STONITH! A faulty member must be killed.You’ll want these settings:
net { 	fencing resource-and-stonith; } 
handlers { 	# Make sure the other node is confirmed 	# dead after this! 	
outdate-peer "/sbin/kill-other-node.sh"; }

Am I missing something or has it changed the way it is defined the stonith script path?

Thanks.

**Comment by rp-** [comment]
which documentation are you refering?

I can't find an `outdate-peer` handler setting in recent [drbd9](https://www.linbit.com/man/v9/?linbitman=drbd.conf.5.html)

**Comment by rck** [comment]
`user/v83/drbdadm_main.c:        /* "outdate-peer" got renamed to fence-peer,`
