### ISSUE TITLE
Can't resize with StandAlone resource

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#204]
Hi, not sure if this expected behavior, so better I'll report this:

One vm has problem with resize disk:

```
Wed Dec 9 17:12:25 2020 : Error executing image transfer script: Command "linstor volume-definition set-size one-vm-7661-disk-0 0 65536M" failed: (Node: 'm13c20') Failed to adjust DRBD resource one-vm-7661-disk-0 Error reports: [ 5FCA5245-E2D0C-043555 ]
```

Live migration also not work due resource creating error:
```
Thu Dec 10 08:39:32 2020 : Error live migrating VM: Command "linstor resource create m15c43 one-vm-7661-disk-0 -s DfltDisklessStorPool" failed: (Node: 'm13c20') Failed to adjust DRBD resource one-vm-7661-disk-0 Error reports: [ 5FCA5245-E2D0C-049127 ]
```

[5FCA5245-E2D0C-049127.log](https://github.com/LINBIT/linstor-server/files/5672009/5FCA5245-E2D0C-049127.log)
[5FCA5245-E2D0C-043555.log](https://github.com/LINBIT/linstor-server/files/5672010/5FCA5245-E2D0C-043555.log)

now resource stuck on:
```
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ ResourceName       ┊ Node   ┊ Port ┊ Usage  ┊ Conns              ┊              State ┊ CreatedOn           ┊
╞═════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ one-vm-7661-disk-0 ┊ m13c20 ┊ 7760 ┊ Unused ┊ StandAlone(m14c11) ┊ Resizing, Outdated ┊                     ┊
┊ one-vm-7661-disk-0 ┊ m13c29 ┊ 7760 ┊ InUse  ┊ Ok                 ┊ Resizing, Diskless ┊ 2020-11-17 09:36:37 ┊
┊ one-vm-7661-disk-0 ┊ m14c11 ┊ 7760 ┊ Unused ┊ Connecting(m13c20) ┊ Resizing, UpToDate ┊                     ┊
┊ one-vm-7661-disk-0 ┊ m15c43 ┊ 7760 ┊ Unused ┊ Connecting(m13c20) ┊           Diskless ┊ 2020-12-10 07:39:20 ┊
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by 71g3pf4c3** [comment]
Has any updates?

**Comment by miyami-32434** [comment]
any update on this?

**Comment by jesulo** [comment]
Hi, how is there a decreasing resize of my ZFS storage with Linstor? Cheers!

**Comment by ghernadi** [comment]
Hi, yes this behavior is indented. A resize event has to be executed by all DRBD-peers for which they need to be connected.
In other words: Only resize if all the peers are healthy. 
If you still run into this error, ignore the error for now (the volumes and the volume-definition will be stuck in resizing), but try to make DRBD healthy again by manually connecting the peers / resolving the StandAlone situation. Once that is done, just re-run the `linstor vd size ...` command (or repeat what ever you did before to trigger the resize again) and it should work afterwards.

@jesulo: Although I think you are a bit off-topic here, shrinking ZFS should be possible with a normal `linstor vd size ...` command. Make sure to shrink whatever is using the volume (maybe an FS) before resizing the volume via LINSTOR.
