### ISSUE TITLE
Can not create snapshots in OpenShift

### ISSUE THREAD

**Issue by dkhachyan** [LINBIT/linstor-server#206]
trying to take a snapshot returns an error:

failed to create snapshot: failed to create snapshot: Message: 'Storage driver 'LVM' does not support snapshots.'

linstor sp list -p shows CanSnapshots: False

**Comment by ghernadi** [comment]
LVM volumes lose performance quite fast when there are snapshots from that volume. That is the main reason Linstor refuses to create snapshots of LVM. 

You can still use LVM-Thin, which has better performance with existing snapshots. Linstor also supports that.

There is already a feature request allowing LVM based snapshots (not only LVM-Thin): https://github.com/LINBIT/linstor-server/issues/148
Although this is on our todo-list, but as the date of the issue shows, it has quite low priority for us.
