### ISSUE TITLE
Autoplacing not working for Diskless pools

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#21]
```
# linstor r c test --auto-place 1 -s DfltDisklessStorPool
ERROR:
Description:
    Not enough available nodes
Details:
    Not enough nodes fulfilling the following auto-place criteria:
     * has a deployed storage pool named 'DfltDisklessStorPool'
     * the storage pool 'DfltDisklessStorPool' has to have at least '1048576' free space
     * the current access context has enough privileges to use the node and the storage pool
     * the node is online
    Auto-placing resource: test
Show reports:
    linstor error-reports show 5BB67EB3-00000-000004
```

**Comment by rp-** [comment]
This is not for what `--auto-place` was designed for.
There is an additional `--diskless-on-remaing` flag that will put the resource diskless on all non replica nodes so combined this would look like this:
`linstor r c test --auto-place 2 --diskless-on-remaining`

I just have found a bug with that command if you have a CONTROLLER node type in your node list, so before you use it remove the CONTROLLER node from your node list.
Will be fixed in the next version.

**Comment by kvaps** [comment]
@rp- I have more than 8 nodes, and `--diskless-on-remaining` not working for me. 

What if I want to place 1 replica in one lvm pool, second replica on second lvm pool.
And then create maximum number of diskless resources (probably 6 of them) on the third diskless pool.

**Comment by kvaps** [comment]
For now I use autoplacing for lvm pools https://github.com/LINBIT/linstor-server/issues/17#issuecomment-425960411

But for diskless pool I should use own implementation, which checks mostly unused nodes in diskless pool, and places resource there

**Comment by raltnoeder** [comment]
DRBD max-peers defaults to 7 (= 8 nodes) in LINSTOR. If you want to deploy resources to more than 8 nodes, this must be set to a higher value, or DRBD will be unable to manage the additional connections.

**Comment by kvaps** [comment]
@raltnoeder any way there is should be some option for automatically place resource with needed replica number per diskless pool

**Comment by ghernadi** [comment]
As mentioned earlier, the autoplacer is designed to choose "diskful" storage pools only. 

Diskless resources are usually used when the user knows from which node they want to access the data of the diskul resources. That means, autoplacing diskless resource is from Linstor's perspective almost never wanted. 
If the user already knows on which node they want to have their diskless resource, a simple `linstor r c ..` does exactly that. Most plugins also use linstor that way - for example "create 2 diskful resource, I dont really care where they are, and I want to access that data from THIS node so I (or the plugin) will create a diskless resource here"

Feel free to reopen this issue if there is another meaningful scenario where autoplacing diskless resources could make sense
