### ISSUE TITLE
can't view files on non-primary nodes.

### ISSUE THREAD

**Issue by httaotao** [LINBIT/linstor-server#215]
hello, everyone, today when I use drbd with single-primary mode, I could not mount the non-primary nodes to check the file.

By the way, I can find the file with  dual-primary mode, but If I mount the two nodes dir, it seems that the synchronization process will stop. so Can I view files on  non-primary nodes? thanks .

the drbd version I used is `8.9.10` on ubuntu 18.04.5 LTS, thanks.

**Comment by rck** [comment]
> hello, everyone, today when I use drbd with single-primary mode, I could not mount the non-primary nodes to check the file.
Not considering dual primary, this is just how DRBD9 works. 1 primary RW, *or* multiple secondaries R.

> By the way, I can find the file with dual-primary mode, but If I mount the two nodes dir, it seems that the synchronization process will stop.

If you do that (mount the FS in dual primary mode) you most likely generate data divergence. mount might be enough. There are only very very specific use cases for dual primary like live migration where the sofware accessing the device (on multiple nodes) guarantees that it only accesses it on one side at a time.

> the drbd version I used is 8.9.10 on ubuntu 18.04.5 LTS, thanks.

the kernel module version is the more important thing here. 8.9.10 is just a pretty old `drbd-utils` version. but that does not matter anyways.

**Comment by httaotao** [comment]
> > hello, everyone, today when I use drbd with single-primary mode, I could not mount the non-primary nodes to check the file.
> 
> Not considering dual primary, this is just how DRBD9 works. 1 primary RW, _or_ multiple secondaries R.
> 
> > By the way, I can find the file with dual-primary mode, but If I mount the two nodes dir, it seems that the synchronization process will stop.
> 
> If you do that (mount the FS in dual primary mode) you most likely generate data divergence. mount might be enough. There are only very very specific use cases for dual primary like live migration where the sofware accessing the device (on multiple nodes) guarantees that it only accesses it on one side at a time.
> 
> > the drbd version I used is 8.9.10 on ubuntu 18.04.5 LTS, thanks.
> 
> the kernel module version is the more important thing here. 8.9.10 is just a pretty old `drbd-utils` version. but that does not matter anyways.

thanks for answer, We hope to find storage systems in low concurrency scenarios. For example, we want to use nfs high availability with drbd, it can use for nexus  and so on. In our intranet environment, there is no high concurrency here.so if I can view files on non-primary nodes, it doesn't matter what mode. we want to realize the mechanism of read-write separation.  
So I’m not sure if this is appropriate. thanks.

**Comment by yusufyildiz** [comment]
Dear @httaotao , What @rck mentions is i believe Read Balancing in DRBD. 
We highly recommend one primary at a time and if needed, you can use read balancing on secondaries. But you cannot mount them. Mount needs to be done in primary node. DRBD prevents you from mounting the secondaries. But it allows reads from the secondaries with DRBD protocol.
