### ISSUE TITLE
linstor-controller info not updated when cluster is upgraded

### ISSUE THREAD

**Issue by gy-lehel** [LINBIT/linstor-server#22]
Cluster of 3 combined nodes is set up, storage-1 is the active controller.
Upgraded and restarted linstor services on storage-1:

root@storage-1:~# linstor node list                                                                                                      
╭───────────────────────────────────────────────────────────────────────────────╮                                                        
┊ Node      ┊ NodeType ┊ Addresses                  ┊ State                     ┊                                                        
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡                                                        
┊ storage-1 ┊ COMBINED ┊ 192.168.220.2:3366 (PLAIN) ┊ Online                    ┊                                                        
┊ storage-2 ┊ COMBINED ┊ 192.168.220.3:3366 (PLAIN) ┊ OFFLINE(VERSION MISMATCH) ┊                                                        
┊ storage-3 ┊ COMBINED ┊ 192.168.220.4:3366 (PLAIN) ┊ OFFLINE(VERSION MISMATCH) ┊                                                        
╰───────────────────────────────────────────────────────────────────────────────╯ 

After upgrading, and restarting storage-2 and storage-3 status of nodes persist until linstor-controller service is restarted a second time on storage-1.

**Comment by rp-** [comment]
internally fixed, will be fixed in the next version
