### ISSUE TITLE
Feature-request: Evacuate

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#220]
# Feature description

Hi, It would be nice to have the following functionality:
```
linstor node evacuate <node> [--timeout <duration>]
```
or
```
linstor storage-pool evacuate <node> <storage-pool> [--timeout <duration>]
```
Then linstor should invoke migration of the diskful DRBD resources to another nodes according resource-group settings.

# Use Case

I see at least two valuable use cases for it:

* **First case** is more common for us, since we're replacing drives quite ofthen we need a reliable way to migrate everything from those drives ad factum.
* **Second case** is more common for OpenShift and Kubernetes enviroments, where compute nodes are usually used to calculate and have no any storage for data. While standard use case for this is to store data on external shared storage system, this approach allows perform rolling-upgrade and automatically scale nodes according the load. Linstor is usually used to store all data on same compute nodes in same cluster, which is making it difficult to update and auto-scaling processes on cluster nodes.
  Provided feature would allow to graceful migrate all resources from the node, before removing it.

**Comment by rp-** [comment]
we have `node evacuate` now
