### ISSUE TITLE
Piraeus supports for arm64

### ISSUE THREAD

**Issue by huchengze** [LINBIT/linstor-server#225]
I have tested various functions of piraeus on x86 machines, and I am very excited about its high availability and high performance, but it seems that piraeus only supports x86 now.

I have successfully completed the arm64 images of all projects written by golang, but I cannot make the arm64 versions of the following two images:
quay.io/piraeusdatastore/piraeus-server
quay.io/piraeusdatastore/drbd9

If you have a plan for piraeus to support arm64, I will do my best to help.

**Comment by ghernadi** [comment]
See https://github.com/piraeusdatastore/piraeus/issues/71
