### ISSUE TITLE
[feature - request] add drbd info as label to linstor volume metrics 

### ISSUE THREAD

**Issue by ddpolyakov** [LINBIT/linstor-server#237]
Hi! It would be very handy to use drbd device label as well as resource name with the volume metrics inside /metrics .  A it awkward not to have such labels while we can get this information with "linstor v l". Thx in advance.

**Comment by rck** [comment]
for additional DRBD metrics you might find that useful as well: https://github.com/LINBIT/drbd-reactor/blob/master/doc/prometheus.md . The rest obviously is up to the LINSTOR devs

**Comment by ddpolyakov** [comment]
> for additional DRBD metrics you might find that useful as well: https://github.com/LINBIT/drbd-reactor/blob/master/doc/prometheus.md . The rest obviously is up to the LINSTOR devs

Thx, I will have a look

**Comment by rp-** [comment]
was added with 1.13.0
