### ISSUE TITLE
add load balance strategies config for nodes in the same storage pool

### ISSUE THREAD

**Issue by redzippo1** [LINBIT/linstor-server#247]
Hi linbiter:

We have a scene is that：
1. we deployed linstor in k8s
2. we use a opeartor for a db system named TIDB
3. we made a scheduler for pod can assign pod to the node where it‘s pv‘s DRDB volume located in (like stork) 

But we found that all the pv's volume (primary + secondery) were assign to only 2 nodes in a 5 nodes storage pool, but we hope it can be more evenly, so we suggest add a configuration for load balance strategie for nodes in the same storage pool.

Thanks a lot !

**Comment by ghernadi** [comment]
You might be interested in increasing the log level to TRACE (see 3rd point [here](https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-linstor-logging) ) and investigate log lines with `Autoplacer`. The current strategies in Linstor are described [here](https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-autoplace-linstor). Any suggestions are welcome

**Comment by redzippo1** [comment]
@ghernadi Thanks for replay.

I have read current strategies in Linstor document, but I feel it's a strategies for choose storage pool, do I wrong？

**Comment by ghernadi** [comment]
No, you are correct. However, the autoplacer chooses from all storage pools, not just from the storage pools of one node - obviously discarding those storage pools where a resource is already deployed, etc...

**Comment by redzippo1** [comment]
@ghernadi Thanks for replay.

Now I create only one storage pool with a zPool in each node added in, should I create storage pool for each signle node (for the volume can be evenly)?

**Comment by ghernadi** [comment]
I am not sure if I understand you correctly here, so let me try to give you an overview: 
In Linstor you have nodes - these correspond to your actual servers.  
Each and every node can have multiple Linstor storage pools - these correspond to i.e. a zpool (or LVM volume group, or ...)
That means, if you have in every server lets say one "large" storage drive and want to use that with Linstor, you will have to create zpools on every node, just as you would do "manually". Afterwards you have to tell Linstor how each of those zpools are named node-local. 
Example: You have 3 nodes, nodeA, nodeB and nodeC. You will need to create zpools on all 3 nodes manually. Lets call all of them `myzpool` for this example. Even in this case, where all zpools are named exactly even, you will still need 3 commands telling Linstor about them:
```
linstor storage-pool create zfs nodeA zfspool myzpool
linstor storage-pool create zfs nodeB zfspool myzpool
linstor storage-pool create zfs nodeB zfspool myzpool
```
whereas `zfspool` is just the name of the Linstor storage pool.

This way, you will end up with 3 storage pools. 
All these 3 storage pools are now considered by the autoplacer with its default configuration.

**Comment by redzippo1** [comment]
I think I have found the key: in my opinion I think after create commands, I will get 1 storage pool with 3 node's zPool in. And the structure looks like below:

```yaml
storage-pools/myzpool:
  - /nodes/nodeA/volumegroup/zfspool
  - /nodes/nodeB/volumegroup/zfspool
  - /nodes/nodeC/volumegroup/zfspool
 ```

After your guide, I have corrected point of my view.
Now I think the strategies for choose storage pool may solve my question.

Thank you!
