### ISSUE TITLE
Snapshot creation during a sync results in inconsistent data

### ISSUE THREAD

**Issue by chiraganand-e2e** [LINBIT/linstor-server#258]
If a resource is syncing on a node, say, after recovery and you take a snapshot of the resource then the snapshot created on this node which is not fully synced is not going to represent the exact state of the resource which is available on other nodes. That is, the data on the snapshot is going to be different on the still syncing node than other nodes.

Is this the intended behaviour?

**Comment by raltnoeder** [comment]
Certainly not intended, there is simply no check implemented for the state of the DRBD device before taking a snapshot. The data on a synchronizing node is inconsistent and therefore unusable. It would make sense for LINSTOR to refuse creating a snapshot on a node that has inconsistent data.

**Comment by rp-** [comment]
we added a check, so every resource needs to be UpToDate to create a snapshot
