### ISSUE TITLE
Resource creation fails due to removed drbdadm option

### ISSUE THREAD

**Issue by gy-lehel** [LINBIT/linstor-server#26]
Resource creatin fails, because drbdadm no longer supports --config-to-exclude switch:

ii  drbd-utils                   9.5.0-1ppa1~bionic2 amd64               RAID 1 over TCP/IP for Linux (user utilities)
ii  linstor-client               0.6.2-1ppa1~bionic1 all                 Linstor client command line tool                                
ii  linstor-common               0.6.5-1ppa1~bionic1 all                 DRBD distributed resource management utility                    
ii  linstor-controller           0.6.5-1ppa1~bionic1 all                 DRBD distributed resource management utility                    
ii  linstor-satellite            0.6.5-1ppa1~bionic1 all                 DRBD distributed resource management utility

ERROR REPORT 5BBDEFE7-0DE37-000004                                  
                                                                                                                                         
============================================================                
                                                                                           
Application:                        LINBIT® LINSTOR                 
Module:                             Satellite                                              
Version:                            0.6.5                           
Build ID:                           d1bd204b9d673f9938226f8c18853e8aae8dd00c
Build time:                         2018-10-02T07:10:01+00:00       
Error time:                         2018-10-11 11:26:01             
Node:                               storage-2                        
                                                                               
============================================================                   
                                                                               
Reported error:                                                                                   
===============                                                                                   
                                                                                                 
Description:                                                                                                              
    Operations on resource 'kubernetes-rd' were aborted                                   
Cause:                                                              
    Verification of resource file failed
Additional information:                                             
    The error reported by the runtime environment or operating system is:                                                                
    The external command 'drbdadm' exited with error code 1         
                                                                                                                               
Category:                           LinStorException                
Class name:                         ResourceException                                                                                    
Class canonical name:               com.linbit.linstor.core.DrbdDeviceHandler.ResourceException
Generated at:                       Method 'createResourceConfiguration', Source file 'DrbdDeviceHandler.java', Line #1371               
                                                                                                                                         
Error message:                      Generated resource file for resource 'kubernetes-rd' is invalid.                                     
                                                                                                                                         
Error context:                                                      
    Generated resource file for resource 'kubernetes-rd' is invalid.
                                                                                                                                         
Call backtrace:                                                     
                                                                                                                                         
    Method                                   Native Class:Line number                                                                    
    createResourceConfiguration              N      com.linbit.linstor.core.DrbdDeviceHandler:1371                                       
    createResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1069                                       
    dispatchResource                         N      com.linbit.linstor.core.DrbdDeviceHandler:311                                        
    run                                      N      com.linbit.linstor.core.DeviceManagerImpl$DeviceHandlerInvocation:1276               
    run                                      N      com.linbit.WorkerPool$WorkerThread:179

Caused by:
==========

Description:
    Execution of the external command 'drbdadm' failed.
Cause:
    The external command exited with error code 1.
Correction:
    - Check whether the external program is operating properly.
    - Check whether the command line is correct.
      Contact a system administrator or a developer if the command line is no longer valid
      for the installed version of the external program.
Additional information:
    The full command line executed was:
    drbdadm --config-to-test /var/lib/linstor.d/kubernetes-rd.res_tmp --config-to-exclude /var/lib/linstor.d/kubernetes-rd.res sh-nop

    The external command sent the following output data:

    The external command sent the follwing error information:
    drbdadm: unrecognized option '--config-to-exclude'

Category:                           LinStorException
Class name:                         ExtCmdFailedException
Class canonical name:               com.linbit.extproc.ExtCmdFailedException
Generated at:                       Method 'execute', Source file 'DrbdAdm.java', Line #445

Error message:                      The external command 'drbdadm' exited with error code 1

Call backtrace:

    Method                                   Native Class:Line number
    execute                                  N      com.linbit.drbd.DrbdAdm:445
    execute                                  N      com.linbit.drbd.DrbdAdm:431
    checkResFile                             N      com.linbit.drbd.DrbdAdm:334
    createResourceConfiguration              N      com.linbit.linstor.core.DrbdDeviceHandler:1364
    createResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1069
    dispatchResource                         N      com.linbit.linstor.core.DrbdDeviceHandler:311
    run                                      N      com.linbit.linstor.core.DeviceManagerImpl$DeviceHandlerInvocation:1276
    run                                      N      com.linbit.WorkerPool$WorkerThread:179

END OF ERROR REPORT.

**Comment by ghernadi** [comment]
Although you do have `ii drbd-utils 9.5.0-1ppa1`, this error looks like you still have an 8.x drbd-kernel loaded. Can you please verify that?

**Comment by gy-lehel** [comment]
Right you are, I wonder how it got in. Could be a missing dependency from drbd-utils to drbd-dkms?

**Comment by rck** [comment]
No. Why would the utils depend on drbd-dkms? That does not make sense. The module could come as part of your distribution kernel (your case), or it could come from a binary kernel module package (how we distribute the kernel module to our customers). dkms is just one possibility one can get a drbd module from.

So you most likely had a drbd.ko loaded, you built a new one (via the dkms), which was placed in some updates directory in the modules tree. But it gets only active if you unload the old one and load the new one.

**Comment by gy-lehel** [comment]
One more thing, with the wrong kernel module, the command fails silently.

**Comment by gy-lehel** [comment]
> No. Why would the utils depend on drbd-dkms? That does not make sense. The module could come as part of your distribution kernel (your case), or it could come from a binary kernel module package (how we distribute the kernel module to our customers). dkms is just one possibility one can get a drbd module from.
> 
> So you most likely had a drbd.ko loaded, you built a new one (via the dkms), which was placed in some updates directory in the modules tree. But it gets only active if you unload the old one and load the new one.

Because I'd expect the package to pull in all of its dependencies upon installation time. In this case the issue was, that the Ubuntu provided drbd package did not clean up the .ko file at the apt purge request, leaving the kernel module there. Since drbd-utils does not express a dependency to a kernel module, the old one was used, and the one matching in version never got installed.

**Comment by ghernadi** [comment]
> One more thing, with the wrong kernel module, the command fails silently.

We know, that's why we implemented a few days ago a DRBD-version check on linstor-satellite startup. Will be included in the next release

**Comment by rck** [comment]
> In this case the issue was, that the Ubuntu provided drbd package did not clean up the .ko file at the apt purge request, leaving the kernel module there. 

No, they only provide the utils, and the .ko is simply part of their kernel packages. You would have to purge your kernel packages to get rid of the .ko (and all of the other modules, drbd.ko is not special in that regard, it is part of their kernel packages).

> Since drbd-utils does not express a dependency to a kernel module, the old one was used, and the one matching in version never got installed.

No. not all all. I already tried to explain that.
