### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by aellert** [LINBIT/linstor-server#261]
Maybe I'm missing something in the doc, but I can't find how to put a node in maintenance.

Presume, I have a 3 node cluster : node1, node2, and node3 and I want to put node1 into maintenance.
I'd like to smoothly switch all Primary resources present on node1 to node 2 and node3 and ideally, node1 should not be a Primary for any resources during the maintenance.

**Comment by chrboe** [comment]
I assume you are using drbd-reactor, in which case that is drbd-reactors job. Just do

```
drbd-reactorctl disable --now
```

on the node in question, and it won't schedule any resources there.
