### ISSUE TITLE
Modify resource definition inserts wrong value in DB

### ISSUE THREAD

**Issue by kiddouk** [LINBIT/linstor-server#264]
Dear all,

Thanks for Linstor, I love it <3

However, with v1.16.0, I have experienced a bug that is easy to reproduce but quite annoying. When modifying a `resource-definition` to change the `--resource-group`, the JavaObject _representation_ is inserted in the ETCD database instead of the value of the object.

Indeed, issuing the command
```
$ etcdctl get /LINSTOR/RESOURCE_DEFINITIONS/PVC-19C03240-C5C2-4215-9F1A-BCB757DCABB6:/RESOURCE_GROUP_NAME
/LINSTOR/RESOURCE_DEFINITIONS/PVC-19C03240-C5C2-4215-9F1A-BCB757DCABB6:/RESOURCE_GROUP_NAME
com.linbit.linstor.core.objects.ResourceGroup@32221ea9
``` 

shows that the value is corrupted.
Note that, when restarting the server, this spawns a critical error of the following kind 

```
Caused by:
==========

Category:                           Exception
Class name:                         InvalidNameException
Class canonical name:               com.linbit.InvalidNameException
Generated at:                       Method 'nameCheck', Source file 'Checks.java', Line #79

Error message:                      Invalid name: Name length 54 is greater than maximum length 48

Call backtrace:

    Method                                   Native Class:Line number
    nameCheck                                N      com.linbit.Checks:79
    <init>                                   N      com.linbit.linstor.core.identifier.ResourceGroupName:18
    build                                    N      com.linbit.linstor.dbdrivers.AbsDatabaseDriver$RawParameters:268
    load                                     N      com.linbit.linstor.core.objects.ResourceDefinitionDbDriver:204
    load                                     N      com.linbit.linstor.core.objects.ResourceDefinitionDbDriver:53
    loadAll                                  N      com.linbit.linstor.dbdrivers.etcd.ETCDEngine:144
    loadAll                                  N      com.linbit.linstor.dbdrivers.AbsDatabaseDriver:100
    loadAll                                  N      com.linbit.linstor.dbdrivers.DatabaseLoader:314
    loadCoreObjects                          N      com.linbit.linstor.core.DbDataInitializer:176
    initialize                               N      com.linbit.linstor.core.DbDataInitializer:108
    startSystemServices                      N      com.linbit.linstor.core.ApplicationLifecycleManager:87
    start                                    N      com.linbit.linstor.core.Controller:345
    main                                     N      com.linbit.linstor.core.Controller:583
```

I would have expected to see the following instead : 
```
$ etcdctl get /LINSTOR/RESOURCE_DEFINITIONS/PVC-19C03240-C5C2-4215-9F1A-BCB757DCABB6:/RESOURCE_GROUP_NAME
/LINSTOR/RESOURCE_DEFINITIONS/PVC-19C03240-C5C2-4215-9F1A-BCB757DCABB6:/RESOURCE_GROUP_NAME
DEFAULT-BACKUP
```

Here is the command to reproduce, at least on `v1.16.0` (using piraeus `v1.7.0-rc.2`) is the following:
`linstor rd modify pvc-19c03240-c5c2-4215-9f1a-bcb757dcabb6 --resource-group default-backup`

I see two errors here : 
1. We do insert the wrong value in DB (object representation instead of object value)
2. We allow to insert some data that cannot be accepted by the DB due to the `ResourceNameGroup` length limit of 48. see https://github.com/LINBIT/linstor-server/blob/fe95a94d86c66c6c9846a3cf579a1a776f95d3f4/server/src/main/java/com/linbit/linstor/core/identifier/ResourceGroupName.java#L9-11 I think that ETCD here doesnt have any rule enforcement when it comes to data, so the code should maybe check by itself. In other DB, this would probably lead to an exception, which is arguably better since it would allow a server restart.

I hope this helps you to find the issue. Please do let me know if you need more info.

Cheers,

**Comment by rp-** [comment]
Just verified that this bug is fixed in linstor 1.17.0
