### ISSUE TITLE
Port Assignment

### ISSUE THREAD

**Issue by iomari** [LINBIT/linstor-server#267]
Greetings,
Is it possible to change the default ports of the controller and the satellite?
The default ports conflict with an existing service. If this is not possible, then we will have to find another storage solution which will be a shame.

Thanks
iomari

**Comment by rp-** [comment]
sure it is possible.
For controller you have the `/etc/linstor/linstor.toml` (with an example file in the same folder).
For the satellite you can place a config file into: `/etc/linstor/linstor_satellite.toml` e.g.:
```
[netcom]
  type="plain"
  port=3367
```

**Comment by iomari** [comment]
Thanks. Out of curiosity, is this documented anywhere? I searched for this in the Linstor docs but couldn't find anything on the config files. And the default toml file is pretty bare.

**Comment by iomari** [comment]
I found it,
https://github.com/LINBIT/linstor-server/blob/master/docs/linstor.toml-example

**Comment by rp-** [comment]
docu updates will soon be in our linstor-guide documentation
