### ISSUE TITLE
LINSTOR 12.3 ADMINISTRATION UNCLEAR 

### ISSUE THREAD

**Issue by shelar1423** [LINBIT/linstor-server#276]
### ****steps to manage LINSTOR cluster 
There is no proper information about the steps to manage LINSTOR cluster.

### #**If a host is also a storage node, it will use a local copy of an image if that is available**
No information about if a host is not a storage node 
 
 A MORE DETAILED INFORMATION IS NEEDED IN THE ADMINISTRATION PART FOR LINSTOR USER GUIDE SO PEOPLE UNDERSTAND IT BETTER
#273

**Comment by shelar1423** [comment]
@ghernadi kindly add label SODACODELOW and SODACODE2022

**Comment by shelar1423** [comment]
@ghernadi  so will this issue be counted for my score in sodacode

**Comment by yusufyildiz** [comment]
Accepted & acknowledged. @shelar1423 Please provide some suggestions on change too.

**Comment by yusufyildiz** [comment]
#SODACODE-issue-Accepted

**Comment by rp-** [comment]
@yusufyildiz can this be closed?
