### ISSUE TITLE
Resource delete + recreate on DRBD sometimes results in out-of-sync data

### ISSUE THREAD

**Issue by elonen** [LINBIT/linstor-server#28]
Every now and then, I've needed to move a DRBD resource to another pool with LINSTOR, and while doing so, I've encountered multiple occasions where out-of-sync data has unexpectedly appeared.

Say I have a resource `resource-name` on POOL_HDD on **node-a** and **node-b**. I want to migrate it to POOL_SSD. What I've done:

```
# linstor r delete node-b resource-name
     (...no errors, all seemingly OK...)
# linstor r create -s POOL_SSD node-b resource-name
     (...no errors, all seemingly OK...)
```

If I've understood these commands correctly, I'd expect the newly created `resource-name` on **node-b** to be in "_inconsistent_" state, and to start immediately pulling data from **node-a**. At times it does, but often `drbdtop` shows disconnected state for the resource, sometimes refusing to connect (citing split brain) except when I do a "discard my data" connect on **node-b**. Even after discarding data on **node-b**, the resource often seems to goes into a "_uptodate_" state immediately, and only running `drbdadm verify` on the resource then reveals out-of-sync data that needs to be fixed by `drbdadm invalidate resource-name` on **node-b**.

-----

POOL_HDD is on _thin LVM on bcache_ at **node-a**, and on _thin LVM on mdadm raid 0_ on **node-b**.
POOL_SSD is on _thin LVM on SSD_ at **node-a**, and _plain LVM on SSD_ at **node-b**.

For DRBD options, I have: `linstor controller drbd-options --sndbuf-size 0 --rcvbuf-size 0 --c-plan-ahead 15 --c-fill-target 40960 --c-min-rate 30720 --c-max-rate 614400 --max-epoch-size 20000 --max-buffers 20000 --verify-alg sha1 --csums-alg sha1`.

Versions:
```
linstor 0.6.2; GIT-hash: 4dcc5834c8bfa6abbfde9f55cdc30114de7630b1

DRBD:
version: 9.0.15-1 (api:2/proto:86-114)
GIT-hash: c46d27900f471ea0f5ba587592439a9ddde1d08b build by root@mox-b, 2018-09-29 22:58:26
Transports (api:16): tcp (9.0.15-1)

Linux 4.17.0-0.bpo.3-amd64 #1 SMP Debian 4.17.17-1~bpo9+1 (2018-08-27) x86_64 GNU/Linux

(Shouldn't matter:)
Proxmox: pve-manager/5.2-9/4b30e8f9 (running kernel: 4.17.0-0.bpo.3-amd64)
linstor-proxmox                      3.0.1-1
```

**Comment by elonen** [comment]
The reason I have a mixed thin/thick setup is that I'm actually trying to migrate away from thin pools. Too much overhead especially on rotating disks, serious problems when metadata fills up etc.

As for rerunning the test, DRBD9 unfortunately seems to be acting up in other ways right night now, so my test results might not be reliable. (I'm getting stuff like
`[37958.172279] drbd vm-100-disk-1/0 drbd1018 mox-a: Online verify found 18446744073709550592 4k blocks out of sync!` The resource size is obviously not 64 zettabytes.)

**Comment by raltnoeder** [comment]
Mixing fat/thin provisioning is only supported on the resource level, but not on the volume level (e.g. one fat volume and one thin volume in the same resource works, but one fat volume on one node and one thin volume on another node does not).
Additionally, with thin provisioning, some of the behavior (connection dropping and split brain) may also be caused by the other peers having used or cleaned up all available peer slots, thereby causing a mismatch of the peers' meta data bitmap generation with the newly created resource's initial generation.
This does not occur with fat provisioned volumes, because those fat provisioned volumes always contain clean/initial meta data that results in a full sync from another peer.

**Comment by elonen** [comment]
Could a mixing thin and thick on different servers be detected? If it's not supported and can lead to problems, maybe the tools should refuse to do so?

**Comment by rp-** [comment]
This is refused now.
