### ISSUE TITLE
ZFS-backed StoragePool: Invalid TotalCapacity

### ISSUE THREAD

**Issue by mheck-lm** [LINBIT/linstor-server#283]
Setting a quota on a ZFS filesystem which is being used as a StoragePool in LINSTOR leads to invalid disk usage information.
The quota seems to be reflected in the "FreeCapacity"-row however the "TotalCapacity"-row does show the total capacity of the ZFS pool.
Therefore depending applications (as the linstor-proxmox plugin) show an invalid disk usage.
![grafik](https://user-images.githubusercontent.com/102594527/160604566-85bb9ed2-abc7-4072-a69a-2d5e6b81da37.png)

**Comment by ghernadi** [comment]
Thanks for the report. This should be fixed in the next release.
