### ISSUE TITLE
Linstor snapshot cloning on zfs fail

### ISSUE THREAD

**Issue by bajizs** [LINBIT/linstor-server#290]
I can't clone drive on zfs. Fro some reason zfs clone get two time the storage pool name. Please see error report below.

ERROR REPORT 6235A28C-FE7EE-000000

============================================================

Application:                        LINBIT® LINSTOR
Module:                             Satellite
Version:                            1.18.0
Build ID:                           648ab925644f53039239c5aec366a11f046f5977
Build time:                         2022-03-15T08:29:07+00:00
Error time:                         2022-04-23 18:58:21
Node:                               hp01

============================================================

Reported error:
===============

Description:
   Failed to restore snapshot 'HDDPool/HDDPool/fileshare_00000@autoSnap00003' into 'HDDPool/backup_2a5036ee_00000'
Additional information:
   Command 'zfs clone HDDPool/HDDPool/fileshare_00000@autoSnap00003 HDDPool/backup_2a5036ee_00000' returned with exitcode 1.  

   Standard out:  

   Error message:  
   cannot open 'HDDPool/HDDPool/fileshare_00000@autoSnap00003': dataset does not exist

Category:                           LinStorException
Class name:                         StorageException
Class canonical name:               com.linbit.linstor.storage.StorageException
Generated at:                       Method 'checkExitCode', Source file 'ExtCmdUtils.java', Line #69

Error message:                      Failed to restore snapshot 'HDDPool/HDDPool/fileshare_00000@autoSnap00003' into 'HDDPool/backup_2a5036ee_00000'

Error context:
   An error occurred while processing resource 'Node: 'hp01', Rsc: 'backup_2a5036ee''

Call backtrace:

   Method                                   Native Class:Line number
   checkExitCode                            N      com.linbit.extproc.ExtCmdUtils:69
   genericExecutor                          N      com.linbit.linstor.layer.storage.utils.Commands:101
   genericExecutor                          N      com.linbit.linstor.layer.storage.utils.Commands:61
   genericExecutor                          N      com.linbit.linstor.layer.storage.utils.Commands:49
   restoreSnapshotFullName                  N      com.linbit.linstor.layer.storage.zfs.utils.ZfsCommands:196
   restoreSnapshot                          N      com.linbit.linstor.layer.storage.zfs.utils.ZfsCommands:182
   restoreSnapshot                          N      com.linbit.linstor.layer.storage.zfs.ZfsProvider:444
   restoreSnapshot                          N      com.linbit.linstor.layer.storage.zfs.ZfsProvider:67
   createVolumes                            N      com.linbit.linstor.layer.storage.AbsStorageProvider:577
   process                                  N      com.linbit.linstor.layer.storage.AbsStorageProvider:398
   process                                  N      com.linbit.linstor.layer.storage.StorageLayer:304
   process                                  N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:847
   processChild                             N      com.linbit.linstor.layer.drbd.DrbdLayer:458
   adjustDrbd                               N      com.linbit.linstor.layer.drbd.DrbdLayer:586
   process                                  N      com.linbit.linstor.layer.drbd.DrbdLayer:393
   process                                  N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:847
   processResourcesAndSnapshots             N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:359
   dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:169
   dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:309
   phaseDispatchDeviceHandlers              N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:1083
   devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:735
   run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:631
   run                                      N      java.lang.Thread:829

END OF ERROR REPORT.

Identical problem with version 1.18.1

**Comment by rp-** [comment]
Thanks for the report, this should be fixed in the next release.
