### ISSUE TITLE
Document downgrade process

### ISSUE THREAD

**Issue by zamazan4ik** [LINBIT/linstor-server#304]
Hi.

After reading the documentation it is not clear for me, how downgrade process should be performed over the solution. Could you please describe somewhere in the documentation:

- How to downgrade Linstor to the older version (hopefully with no downtime)

Thanks in advance!

**Comment by ghernadi** [comment]
Short answer: Linstor does not have a downgrade path. 

Longer answer: The main problem is the database. If it changed, I would highly discourage from downgrading. Even if during a migration usually database columns or tables are added (which can be ignored after a downgrade), in some migrations we had to change values of existing entries. When such changes are ignored / not reverted, things could go very wrong. 

If you are interested in when Linstor's DB changed, take a look at https://github.com/LINBIT/linstor-server/tree/master/controller/src/main/java/com/linbit/linstor/dbcp/migration for SQL migrations and the corresponding sub-packages for ETCD / K8s.
