### ISSUE TITLE
StorDriver/LvcreateOptions option is not considered for create thin LVM

### ISSUE THREAD

**Issue by cduchenoy** [LINBIT/linstor-server#343]
Hi,

I use this configuration to add a tag on each drbd resource

`$ linstor controller set-property StorDriver/LvcreateOptions '--addtag drbd'`

I get this (on lvmthin create):

`DEBUG LINSTOR/Satellite - SYSTEM - Executing command: lvcreate --config devices { filter=['a|/dev/sdb1|','r|.*|'] } --virtualsize 1048840k vg_ssd --thinpool thin-ssd --name vm-110-disk-7_00000`

With this patch everythin is ok:

```patch
$ diff -Naur ./satellite/src/main/java/com/linbit/linstor/layer/storage/lvm/LvmThinProvider.java{.org,}
--- ./satellite/src/main/java/com/linbit/linstor/layer/storage/lvm/LvmThinProvider.java.org	2023-03-16 23:23:32.599340966 +0000
+++ ./satellite/src/main/java/com/linbit/linstor/layer/storage/lvm/LvmThinProvider.java	2023-03-16 22:56:34.671419392 +0000
@@ -147,7 +147,8 @@
                     vlmData.getThinPool(),
                     lvId,
                     vlmData.getExpectedSize(),
-                    config
+                    config,
+                    additionalOptionsArr
                 )
             );
             LvmUtils.execWithRetry(
```

**Comment by cduchenoy** [comment]
With this patch the LvcreateOptions property is not applied for the creation of snapshots

So we applied a workaround:

```patch
# remove LvcreateOptions
linstor controller set-property StorDriver/LvcreateOptions

# patch
root@lxc-docker-client:/opt/linstor-server# diff -Naur ./satellite/src/main/java/com/linbit/linstor/layer/storage/lvm/utils/LvmCommands.java{.org,}
--- ./satellite/src/main/java/com/linbit/linstor/layer/storage/lvm/utils/LvmCommands.java.org   2023-03-17 04:39:41.102371811 +0100
+++ ./satellite/src/main/java/com/linbit/linstor/layer/storage/lvm/utils/LvmCommands.java       2023-03-17 04:58:03.432655399 +0100
@@ -131,6 +131,7 @@
                 "--size", size + "k",
                 volumeGroup,
                 "-n", vlmId,
+                "--addtag", "drbd", // Geco-it force addtag
                 "-y" // force, skip "wipe signature question"
             ),
             "Failed to create lvm volume",
@@ -327,6 +328,7 @@
                 "--setactivationskip", "y", // snapshot needs to be active from
                 "--ignoreactivationskip", // the beginning for
                 "--activate", "y", // snapshot-shipping to work
+                "--addtag", "drbd", // Geco-it force addtag
                 "--name", snapshotIdentifier,
                 volumeGroup + File.separator + identifier
             ),
@@ -353,6 +355,7 @@
                 lvmConfig,
                 (Collection<String>) null,
                 "--snapshot",
+                "--addtag", "drbd", // Geco-it force addtag
                 "--name", targetId,
                 volumeGroup + File.separator + sourceLvIdWithSnapName
             ),
root@lxc-docker-client:/opt/linstor-server#
```

**Comment by ghernadi** [comment]
Good catch. I like the first patch more, since it is more generic. Regarding the snapshots: I guess you missed the `createSnapshot` method in `LvmThinProvider`, although `LvmCommands#createSnapshotThin` needs to be extended with that parameter similar to `LvmCommands#createThin`. Speaking of extending methods: there are also a few other methods in `LvmThinProvider` that should be extended to consider / use the `StorDriver/LvcreateOptions` property. 

Same goes for ZFS. 

I'll add it to my todo list.

**Comment by cduchenoy** [comment]
Yes that's what I had seen but as I'm not a developer but a sysadmin so I made a hacky patch 

Indeed I think that it would be necessary to make two options by fs to cover all the possibilities

* ZfsCreateOptions / ZfsSnapshotOption
* LvCreateOptions / LvSnapshotOption

**Comment by cduchenoy** [comment]
Hi, Thank you so much !

With the new version 1.22 (90a6646) everything works fine
