### ISSUE TITLE
Upgrade from DRBD Manage to LINSTOR

### ISSUE THREAD

**Issue by haySwim** [LINBIT/linstor-server#35]
> I do understand that the initial set-up for LINSTOR is more difficult, but it's the successor to DRBD Manage and is in every way better.

Is it possible to move from drbdmanage to linstore without loosing already configured resources?
I've a two node kubernetes setup with drbd-flex-provision on both nodes and would love to switch from drbdmanage to linstore.
Are there any guides on howto "upgrade" drbdmanage to linstore?

Best Regards
Andreas

_Originally posted by @adoerler in https://github.com/LINBIT/drbd-flex-provision/issues/8#issuecomment-436426273_

**Comment by rp-** [comment]
see the documentation at: https://docs.linbit.com/docs/users-guide-9.0/#s-linstor-migrate-from-dm

**Comment by adoerler** [comment]
Thank you rp-, I'll give it a try!
