### ISSUE TITLE
Can't delete backup schedule due of unknown exception

### ISSUE THREAD

**Issue by duckhawk** [LINBIT/linstor-server#362]
While trying to delete linstor backup schedule there is "unknown exception" error.
```
root@master1:~# linstor schedule delete backups
ERROR:

Description:
    Deletion of schedule 'backups' failed due to an unknown exception.
Details:
    Schedule: backups
Show reports:
    linstor error-reports show 64912F51-00000-000010
command terminated with exit code 10
```
AFAIK, there was no actions, that can lead to this behaviour
I'll attach log with error report.
[schedule-deletion-error.txt](https://github.com/LINBIT/linstor-server/files/11816334/schedule-deletion-error.txt)

**Comment by jokucera** [comment]
Thank you for the report! Not only was I able to fix this error, but during trying to reproduce this issue I also stumbled upon a different bug. Both are now fixed and will be included in the next release.
