### ISSUE TITLE
Deleted resources in "linstor advise"

### ISSUE THREAD

**Issue by duckhawk** [LINBIT/linstor-server#368]
Having multiple recomendations in "linstor advise resources" about some volumes, that already deleted from cluster

```
root@master1:~# linstor advise r
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Resource                                 | Issue                                             | Possible fix                                                           |
|=======================================================================================================================================================================|
| pvc-00bc6c27-b35e-4408-88a9-88128ca33d46 | Resource expected to have 1 replicas, got only 0. | linstor rd ap --place-count 1 pvc-00bc6c27-b35e-4408-88a9-88128ca33d46 |
| pvc-01708592-4aca-4a87-a065-cf3eba9e74f5 | Resource expected to have 2 replicas, got only 0. | linstor rd ap --place-count 2 pvc-01708592-4aca-4a87-a065-cf3eba9e74f5 |
| pvc-02bbdf38-c9ff-4870-9458-473debcead5f | Resource expected to have 2 replicas, got only 0. | linstor rd ap --place-count 2 pvc-02bbdf38-c9ff-4870-9458-473debcead5f |
| pvc-03eab4d1-796d-4406-bcd6-7da38c6df122 | Resource expected to have 1 replicas, got only 0. | linstor rd ap --place-count 1 pvc-03eab4d1-796d-4406-bcd6-7da38c6df122 |
| pvc-0405438c-640d-4a1d-bd35-e90ff6572a19 | Resource expected to have 1 replicas, got only 0. | linstor rd ap --place-count 1 pvc-0405438c-640d-4a1d-bd35-e90ff6572a19 |
| pvc-05eedc9a-d833-4dc7-b17a-e69e3808634f | Resource expected to have 1 replicas, got only 0. | linstor rd ap --place-count 1 pvc-05eedc9a-d833-4dc7-b17a-e69e3808634f |

```
Is it normal situation? How can I remove them?

**Comment by ghernadi** [comment]
Having 0 resources raises the question why the resource-definition even exists... 
So if you want to get rid of these "advises", first make sure that in your K8s setup those resources are already gone / no longer needed, and afterwards try deleting the resource-definition.

**Comment by duckhawk** [comment]
Yes, I forgot about resource-definitions.
There was 150+ of rd, that wasn't deleted by controller. I don't understand, it's look like he almost didn't cleaned it :(

**Comment by ghernadi** [comment]
Do I understand you correctly that you tried to delete the entire resource (RD in Linstor) via K8s? 

If so, is it possible that it ran into some error, Linstor kept the resource in DELETING state for a while, at some point K8s/CSI gave up with its cleanup procedure, then later Linstor did manage to get rid of the resource but at this point K8s already gave up trying to properly clean up the rest (i.e. the RD)?

Or an alternative idea what could have caused such errors are snapshots of the resource. You cannot delete a resource-definition as long as it has snapshots. That means you need to get rid of those snapshots before deleting the resource-definition (this might be a cause why K8s failed to delete the RD in the first idea).

**Comment by duckhawk** [comment]
Mostly, I'd deleted resource, not resource-definition. (in k8s there was Retain mode for PV, so it needed manual resources cleanup)

**Comment by ghernadi** [comment]
I see. In that case I'd guess that simply nobody / nothing tried to delete the resource-definition, so you will have to delete them as well when cleaning up manually.

As a hint: if you call `linstor rd d $rsc`, Linstor will automatically delete all of the RD's resources as well and afterwards delete the RD, so in case you ran `linstor r d $nodea $rsc; linstor r d $nodeb $rsc; ...` until now, the `rd d` method might be easier for you

**Comment by duckhawk** [comment]
Thank you for answers!
