### ISSUE TITLE
Feature request: High availability on Linstor changes

### ISSUE THREAD

**Issue by alexisries** [LINBIT/linstor-server#40]
# Feature request

## Problem

When a satellite is offline and we want to apply changes such as deleting a node for a resource or expanding a volume dependent on that satellite, that change is queued and will only be executed when the connection of all the satellites will be restored.

This means that when a node is dead, we can no longer expand the resources or delete a resource on another node, so there is a problem of high availability.

## Idea of solution

It would be interesting, therefore, for Linstor to act differently when a satellite is offline.
All drbd connections must be interrupted on the offline nodes and changes must be saved to be executed when the satellite is re-established. This would ensure that changes are immediately applied to online satellites despite the fact that a satellite is offline.

**Comment by raltnoeder** [comment]
The only case I could possibly imagine being able to work with offline nodes is the resize case. LINSTOR could possibly try to resize if both, the satellite connection and the DRBD resource connection to the node are down. The DRBD resource on that node would then remain unusable until the resize completes successfully on that node.

Resizing a DRBD resource that is connected without a satellite connection to that node is impossible, because the DRBD resize fails on all other nodes if one of the connected nodes does not have enough backend storage capacity.
Keeping DRBD connections online if the satellite connection is down is an intentional design feature (separation of control plane and data plane).

**Comment by alexisries** [comment]
> The only case I could possibly imagine being able to work with offline nodes is the resize case. 

Yes, but when a resource is deployed on three nodes, one of which is offline and I delete the resource on one of the online nodes, the deletion is put in the background and is executed only when all the nodes are online.

Which means that when I delete the deployment on a node and I redeploy on the same node, I have the following error on the controller: 
`A resource" CV_b42f0f42-9504-42fc-b3e0-583bc0b5493c 'on node' os-compute-2 'already exists`

This is problematic in an OpenStack environment, the same operation will be performed if a user detaches a volume from one instance to attach it to another instance on the same physical compute node.

Is it possible to cancel the deletion of a resource if I redeploy the same resource on the same node?


> Keeping DRBD connections online if the satellite connection is down is an intentional design feature (separation of control plane and data plane).

I understand, this avoids the split-brain caused by the control layer in case of inconsistency between the satellites. There remains the problem of re-deploying a resource on the same node.

**Comment by alexisries** [comment]
Hi woojay,

Cinder and Linstor are configured to deploy new cinder volumes on both storage backends.

1. Let's create a cinder volume of 1G.
2. We attach this volume to an instance by the dashboard, a diskless resource is deployed by the Cinder driver on the compute node of the instance.
3. Now we stop a satellite service to simulate the loss of a storage backend.
4. Detach the instance volume now.
5. Reattach the volume to the same instance or to another instance on the same compute node.

The volume remains detached because the driver is in error because of the following error on the Linstor side:

`A resource' CV_b42f0f42-9504-42fc-b3e0-583bc0b5493c 'on node' os-compute-2 'already exists`

Linstor displays 'DELETING' at the 'linstor resource list' command output and does not change until the satellite is restored.

**Comment by alexisries** [comment]
After reflecting and rereading the previous comments I realize that this is not really a problem if users can not interact with a resource that is degraded by an offline satellite as long as we can do a `node lost <nodeName>` as mentioned by @ghernadi . 
The failure would only be temporary and we would have time to restore to the storage backend with this command.

Thank you all

**Comment by alexisries** [comment]
OK, I understand, thank you for everything.
