### ISSUE TITLE
proxmox-kernel-6.8 dkms/DRBD failed

### ISSUE THREAD

**Issue by t0mat000** [LINBIT/linstor-server#405]
Hi,

we cant install the new PVE Kernel. DKMS failed. Any Ideas?

**apt dist-upgrade** 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up proxmox-kernel-6.8.4-2-pve (6.8.4-2) ...
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/dkms 6.8.4-2-pve /boot/vmlinuz-6.8.4-2-pve
dkms: running auto installation service for kernel 6.8.4-2-pve.
Sign command: /lib/modules/6.8.4-2-pve/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j12 KERNELRELEASE=6.8.4-2-pve -C src/drbd KDIR=/lib/modules/6.8.4-2-pve/build..............(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.8.4-2-pve (x86_64)
Consult /var/lib/dkms/drbd/9.2.8-2/build/make.log for more information.
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
dkms: autoinstall for kernel: 6.8.4-2-pve failed!
run-parts: /etc/kernel/postinst.d/dkms exited with return code 11
Failed to process /etc/kernel/postinst.d at /var/lib/dpkg/info/proxmox-kernel-6.8.4-2-pve.postinst line 20.
dpkg: error processing package proxmox-kernel-6.8.4-2-pve (--configure):
 installed proxmox-kernel-6.8.4-2-pve package post-installation script subprocess returned error exit status 2
dpkg: dependency problems prevent configuration of proxmox-kernel-6.8:
 proxmox-kernel-6.8 depends on proxmox-kernel-6.8.4-2-pve-signed | proxmox-kernel-6.8.4-2-pve; however:
  Package proxmox-kernel-6.8.4-2-pve-signed is not installed.
  Package proxmox-kernel-6.8.4-2-pve is not configured yet.

dpkg: error processing package proxmox-kernel-6.8 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of proxmox-default-kernel:
 proxmox-default-kernel depends on proxmox-kernel-6.8; however:
  Package proxmox-kernel-6.8 is not configured yet.

dpkg: error processing package proxmox-default-kernel (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of proxmox-ve:
 proxmox-ve depends on proxmox-default-kernel; however:
  Package proxmox-default-kernel is not configured yet.

dpkg: error processing package proxmox-ve (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 proxmox-kernel-6.8.4-2-pve
 proxmox-kernel-6.8
 proxmox-default-kernel
 proxmox-ve
E: Sub-process /usr/bin/dpkg returned an error code (1)

**cat /var/lib/dkms/drbd/9.2.8-2/build/make.log**
DKMS make.log for drbd-9.2.8-2 for kernel 6.8.4-2-pve (x86_64)
Wed Apr 24 03:47:05 PM CEST 2024
make: Entering directory '/var/lib/dkms/drbd/9.2.8-2/build/src/drbd'

    Calling toplevel makefile of kernel source tree, which I believe is in
    KDIR=/lib/modules/6.8.4-2-pve/build

cat /dev/null   > Module.symvers
make -C /lib/modules/6.8.4-2-pve/build   M=/var/lib/dkms/drbd/9.2.8-2/build/src/drbd  modules "PRE_CFLAGS="
  COMPAT  __vmalloc_has_2_params
  COMPAT  add_disk_returns_int
  COMPAT  before_4_13_kernel_read
  COMPAT  bio_alloc_has_4_params
  COMPAT  blkdev_get_by_path_has_holder_ops
  COMPAT  blkdev_issue_discard_takes_flags
  COMPAT  blkdev_issue_zeroout_discard
  COMPAT  blkdev_put_has_holder
  COMPAT  block_device_operations_open_takes_gendisk
  COMPAT  block_device_operations_release_takes_single_argument
  COMPAT  can_include_vermagic_h
  COMPAT  dax_direct_access_takes_mode
  COMPAT  fs_dax_get_by_bdev_takes_start_off
  COMPAT  fs_dax_get_by_bdev_takes_start_off_and_holder
  COMPAT  genl_policy_in_ops
  COMPAT  have_BIO_MAX_VECS
  COMPAT  have_CRYPTO_TFM_NEED_KEY
  COMPAT  have_GENHD_FL_NO_PART
  COMPAT  have_SHASH_DESC_ON_STACK
  COMPAT  have_WB_congested_enum
  COMPAT  have___bio_add_page
  COMPAT  have_allow_kernel_signal
  COMPAT  have_bdev_discard_granularity
  COMPAT  have_bdev_max_discard_sectors
  COMPAT  have_bdev_nr_sectors
  COMPAT  have_bdevname
  COMPAT  have_bdgrab
  COMPAT  have_bdi_congested
  COMPAT  have_bdi_congested_fn
  COMPAT  have_bio_advance_iter_single
  COMPAT  have_bio_alloc_clone
  COMPAT  have_bio_bi_bdev
  COMPAT  have_bio_bi_error
  COMPAT  have_bio_bi_opf
  COMPAT  have_bio_bi_status
  COMPAT  have_bio_clone_fast
  COMPAT  have_bio_op_shift
  COMPAT  have_bio_set_dev
  COMPAT  have_bio_set_op_attrs
  COMPAT  have_bio_split_to_limits
  COMPAT  have_bio_start_io_acct
  COMPAT  have_bioset_init
  COMPAT  have_bioset_need_bvecs
  COMPAT  have_blk_alloc_disk
  COMPAT  have_blk_alloc_queue_rh
  COMPAT  have_blk_check_plugged
  COMPAT  have_blk_cleanup_disk
  COMPAT  have_blk_mode_t
  COMPAT  have_blk_opf_t
  COMPAT  have_blk_qc_t_make_request
  COMPAT  have_blk_qc_t_submit_bio
  COMPAT  have_blk_queue_flag_set
  COMPAT  have_blk_queue_make_request
  COMPAT  have_blk_queue_max_write_same_sectors
  COMPAT  have_blk_queue_merge_bvec
  COMPAT  have_blk_queue_split_bio
  COMPAT  have_blk_queue_split_q_bio
  COMPAT  have_blk_queue_split_q_bio_bioset
  COMPAT  have_blk_queue_update_readahead
  COMPAT  have_blk_queue_write_cache
  COMPAT  have_bvec_kmap_local
  COMPAT  have_d_inode
  COMPAT  have_disk_update_readahead
  COMPAT  have_enum_req_op
  COMPAT  have_fallthrough
  COMPAT  have_fs_dax_get_by_bdev
  COMPAT  have_generic_start_io_acct_q_rw_sect_part
  COMPAT  have_generic_start_io_acct_rw_sect_part
  COMPAT  have_genl_info_userhdr
  COMPAT  have_get_random_u32
  COMPAT  have_get_random_u32_below
  COMPAT  have_hd_struct
  COMPAT  have_ib_cq_init_attr
  COMPAT  have_ib_get_dma_mr
  COMPAT  have_idr_is_empty
  COMPAT  have_inode_lock
  COMPAT  have_kmap_local_page
  COMPAT  have_ktime_to_timespec64
  COMPAT  have_kvfree
  COMPAT  have_kvfree_rcu
  COMPAT  have_kvfree_rcu_mightsleep
  COMPAT  have_list_is_first
  COMPAT  have_list_next_entry
  COMPAT  have_lookup_user_key
  COMPAT  have_max_send_recv_sge
  COMPAT  have_msg_splice_pages
  COMPAT  have_nla_nest_start_noflag
  COMPAT  have_nla_parse_deprecated
  COMPAT  have_nla_put_64bit
  COMPAT  have_nla_strscpy
  COMPAT  have_part_stat_h
  COMPAT  have_part_stat_read_accum
  COMPAT  have_pointer_backing_dev_info
  COMPAT  have_proc_create_single
  COMPAT  have_queue_flag_discard
  COMPAT  have_queue_flag_stable_writes
  COMPAT  have_rb_declare_callbacks_max
  COMPAT  have_refcount_inc
  COMPAT  have_req_hardbarrier
  COMPAT  have_req_noidle
  COMPAT  have_req_nounmap
  COMPAT  have_req_op_write
  COMPAT  have_req_op_write_zeroes
  COMPAT  have_req_write
  COMPAT  have_revalidate_disk_size
  COMPAT  have_sched_set_fifo
  COMPAT  have_sched_signal_h
  COMPAT  have_security_netlink_recv
  COMPAT  have_sendpage_ok
  COMPAT  have_set_capacity_and_notify
  COMPAT  have_shash_desc_zero
  COMPAT  have_simple_positive
  COMPAT  have_sk_use_task_frag
  COMPAT  have_sock_set_keepalive
  COMPAT  have_strscpy
  COMPAT  have_struct_bvec_iter
  COMPAT  have_struct_size
  COMPAT  have_submit_bio_noacct
  COMPAT  have_tasklet_setup
  COMPAT  have_tcp_sock_set_cork
  COMPAT  have_tcp_sock_set_keepcnt
  COMPAT  have_tcp_sock_set_keepidle
  COMPAT  have_tcp_sock_set_nodelay
  COMPAT  have_tcp_sock_set_quickack
  COMPAT  have_time64_to_tm
  COMPAT  have_timer_setup
  COMPAT  have_timer_shutdown
  COMPAT  have_tls_get_record_type
  COMPAT  have_tls_tx_rx
  COMPAT  have_void_make_request
  COMPAT  have_void_submit_bio
  COMPAT  ib_alloc_pd_has_2_params
  COMPAT  ib_device_has_ops
  COMPAT  ib_post_send_const_params
  COMPAT  ib_query_device_has_3_params
  COMPAT  need_drbd_wrappers
  COMPAT  need_make_request_recursion
  COMPAT  need_skb_abort_seq_read
  COMPAT  part_stat_read_takes_block_device
  COMPAT  queue_limits_has_discard_zeroes_data
  COMPAT  rdma_create_id_has_net_ns
  COMPAT  rdma_reject_has_reason_arg
  COMPAT  sk_data_ready_has_1_param
  COMPAT  sock_create_kern_has_netns_parameter
  COMPAT  sock_ops_returns_addr_len
  COMPAT  struct_gendisk_has_backing_dev_info
  UPD     /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/compat.6.8.4-2-pve.h
  UPD     /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/compat.h
  GENPATCHNAMES   6.8.4-2-pve
  SPATCH   7ead2cd555af38022b5d4b5b71d24005  6.8.4-2-pve
  PATCH
patching file drbd_nl.c
patching file drbd_debugfs.c
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_dax_pmem.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_debugfs.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_bitmap.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_proc.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_sender.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_req.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_actlog.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_main.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_strings.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_interval.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_state.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd-kernel-compat/drbd_wrappers.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nla.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_transport.o
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_transport_tcp.o
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_main.c:2897:6: warning: no previous prototype for ‘drbd_fsync_device’ [-Wmissing-prototypes]
 2897 | void drbd_fsync_device(struct drbd_device *device)
      |      ^~~~~~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c: In function ‘close_backing_dev’:
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:2719:9: error: implicit declaration of function ‘blkdev_put’; did you mean ‘dev_put’? [-Werror=implicit-function-declaration]
 2719 |         blkdev_put(bdev, FMODE_READ | FMODE_WRITE | FMODE_EXCL);
      |         ^~~~~~~~~~
      |         dev_put
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:2719:53: error: ‘FMODE_EXCL’ undeclared (first use in this function); did you mean ‘FMODE_EXEC’?
 2719 |         blkdev_put(bdev, FMODE_READ | FMODE_WRITE | FMODE_EXCL);
      |                                                     ^~~~~~~~~~
      |                                                     FMODE_EXEC
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:2719:53: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c: In function ‘open_backing_dev’:
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:2741:37: error: implicit declaration of function ‘blkdev_get_by_path’; did you mean ‘bdev_open_by_path’? [-Werror=implicit-function-declaration]
 2741 |         struct block_device *bdev = blkdev_get_by_path(bdev_path,
      |                                     ^~~~~~~~~~~~~~~~~~
      |                                     bdev_open_by_path
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:2742:62: error: ‘FMODE_EXCL’ undeclared (first use in this function); did you mean ‘FMODE_EXEC’?
 2742 |                                   FMODE_READ | FMODE_WRITE | FMODE_EXCL,
      |                                                              ^~~~~~~~~~
      |                                                              FMODE_EXEC
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c: At top level:
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:3075:5: warning: no previous prototype for ‘drbd_md_read’ [-Wmissing-prototypes]
 3075 | int drbd_md_read(struct drbd_config_context *adm_ctx, struct drbd_backing_dev *bdev)
      |     ^~~~~~~~~~~~
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_transport_lb-tcp.o
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:6652:5: warning: no previous prototype for ‘param_set_drbd_strict_names’ [-Wmissing-prototypes]
 6652 | int param_set_drbd_strict_names(const char *val, const struct kernel_param *kp)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_transport_rdma.o
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.c:7328:5: warning: no previous prototype for ‘notify_path_state’ [-Wmissing-prototypes]
 7328 | int notify_path_state(struct sk_buff *skb,
      |     ^~~~~~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c: In function ‘convert_state’:
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6568:27: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6568 |                 [L_OFF] = L_OFF,
      |                           ^~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6569:35: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6569 |                 [L_ESTABLISHED] = L_ESTABLISHED,
      |                                   ^~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6571:39: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6571 |                 [L_STARTING_SYNC_S] = L_STARTING_SYNC_T,
      |                                       ^~~~~~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6572:39: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6572 |                 [L_STARTING_SYNC_T] = L_STARTING_SYNC_S,
      |                                       ^~~~~~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6573:35: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6573 |                 [L_WF_BITMAP_S] = L_WF_BITMAP_T,
      |                                   ^~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6574:35: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6574 |                 [L_WF_BITMAP_T] = L_WF_BITMAP_S,
      |                                   ^~~~~~~~~~~~~
/var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_receiver.c:6577:38: warning: implicit conversion from ‘enum drbd_repl_state’ to ‘enum drbd_conn_state’ [-Wenum-conversion]
 6577 |                 [L_VERIFY_S]       = L_VERIFY_T,
      |                                      ^~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:243: /var/lib/dkms/drbd/9.2.8-2/build/src/drbd/drbd_nl.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1926: /var/lib/dkms/drbd/9.2.8-2/build/src/drbd] Error 2
make: *** [Makefile:184: kbuild] Error 2
make: Leaving directory '/var/lib/dkms/drbd/9.2.8-2/build/src/drbd'

**Comment by rp-** [comment]
Wrong project, but I think 9.2.8 just doesn't work with kernel 6.8 yet?
@rck

**Comment by rck** [comment]
correct. I tested the kernel module 9.2.9-rc.1 which then works with the new PVE kernel.

**Comment by t0mat000** [comment]
@rp- : thx, what is the correct project?

@rck  thx, how long must we wait this time?

**Comment by rck** [comment]
> @rp- : thx, what is the correct project?

if drbd does not compile, then the drbd project (https://github.com/LINBIT/drbd/)

> @rck thx, how long must we wait this time?

the RC was on Tue, I'd guess early next week
