### ISSUE TITLE
Linstore controller is not reaching its database & health API returns HTTP 500

### ISSUE THREAD

**Issue by SystemFuchs** [LINBIT/linstor-server#419]
I installed a 3 node Proxmox cluster with Linstor installed according to blog posts. Setup Linstor controller in HA mode managed by drbd-reactor service. When a cluster node is rebooted the controller service is automatically activated on one of the remaining nodes.

After the rebooted nodes comes up the Linstor satellite on the rebooted node will not connect automatically to the controller again. So I use the command `linstor node reconnect <nodename>`

Checking the Linstor controller logs everthing seems fine but the log gets spammed with the following message followed by an uncaught exception:

Sep 26 10:28:10 minis03 Controller[821851]: 2024-09-26 10:28:10.917 [grizzly-http-server-6] INFO  LINSTOR/Controller/16373c SYSTEM - REST/API RestClient(192.168.178.201; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:17 minis03 Controller[821851]: 2024-09-26 10:28:17.692 [grizzly-http-server-8] INFO  LINSTOR/Controller/f4e275 SYSTEM - REST/API RestClient(192.168.178.202; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:17 minis03 Controller[821851]: 2024-09-26 10:28:17.828 [grizzly-http-server-10] INFO  LINSTOR/Controller/9f4c02 SYSTEM - REST/API RestClient(192.168.178.202; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:20 minis03 Controller[821851]: 2024-09-26 10:28:20.318 [grizzly-http-server-12] INFO  LINSTOR/Controller/e431b3 SYSTEM - REST/API RestClient(192.168.178.201; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:20 minis03 Controller[821851]: 2024-09-26 10:28:20.326 [grizzly-http-server-14] INFO  LINSTOR/Controller/dc4a87 SYSTEM - REST/API RestClient(192.168.178.201; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:21 minis03 Controller[821851]: 2024-09-26 10:28:21.136 [grizzly-http-server-16] INFO  LINSTOR/Controller/1b470f SYSTEM - REST/API RestClient(192.168.178.203; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:21 minis03 Controller[821851]: 2024-09-26 10:28:21.456 [grizzly-http-server-18] INFO  LINSTOR/Controller/1bb538 SYSTEM - REST/API RestClient(192.168.178.203; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:27 minis03 Controller[821851]: 2024-09-26 10:28:27.507 [grizzly-http-server-20] INFO  LINSTOR/Controller/1bf5d8 SYSTEM - REST/API RestClient(192.168.178.202; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:27 minis03 Controller[821851]: 2024-09-26 10:28:27.634 [grizzly-http-server-22] INFO  LINSTOR/Controller/ed4913 SYSTEM - REST/API RestClient(192.168.178.202; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:30 minis03 Controller[821851]: 2024-09-26 10:28:30.481 [grizzly-http-server-24] INFO  LINSTOR/Controller/0ea7dd SYSTEM - REST/API RestClient(192.168.178.203; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:30 minis03 Controller[821851]: 2024-09-26 10:28:30.624 [grizzly-http-server-26] INFO  LINSTOR/Controller/bebc39 SYSTEM - REST/API RestClient(192.168.178.203; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:31 minis03 Controller[821851]: 2024-09-26 10:28:31.119 [grizzly-http-server-28] INFO  LINSTOR/Controller/bdcdb0 SYSTEM - REST/API RestClient(192.168.178.201; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:31 minis03 Controller[821851]: 2024-09-26 10:28:31.127 [grizzly-http-server-30] INFO  LINSTOR/Controller/0bdecb SYSTEM - REST/API RestClient(192.168.178.201; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:38 minis03 Controller[821851]: 2024-09-26 10:28:38.019 [grizzly-http-server-32] INFO  LINSTOR/Controller/b7f249 SYSTEM - REST/API RestClient(192.168.178.202; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:38 minis03 Controller[821851]: 2024-09-26 10:28:38.273 [grizzly-http-server-34] INFO  LINSTOR/Controller/d1cc74 SYSTEM - REST/API RestClient(192.168.178.202; 'linstor-proxmox/8.0.4')/QryAllSizeInfo
Sep 26 10:28:39 minis03 Controller[821851]: 2024-09-26 10:28:39.463 [SpaceTrackingService] ERROR LINSTOR/Controller/ SYSTEM - Uncaught exception in j [Report number 66F51ABE-00000-000001]`

`root@minis02:~# wget http://192.168.178.203:3370/health
--2024-09-26 10:30:14--  http://192.168.178.203:3370/health
Connecting to 192.168.178.203:3370... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2024-09-26 10:30:14 ERROR 500: Internal Server Error.`

`
root@minis01:~# linstor err list

┊ 66F3D39C-82B5E-000000 ┊ 2024-09-25 13:57:49 ┊ S|minis02 ┊ SocketException: Connection reset             ┊
┊ 66F3FCF8-00000-000000 ┊ 2024-09-25 14:07:22 ┊ C|minis03 ┊ LinStorException: Cannot connect to satellite ┊
┊ 66F3FCF8-00000-000001 ┊ 2024-09-25 14:09:22 ┊ C|minis03 ┊ ImplementationError: Uncaught exception in j  ┊
┊ 66F51ABE-00000-000000 ┊ 2024-09-26 10:26:39 ┊ C|minis03 ┊ LinStorException: Cannot connect to satellite ┊
┊ 66F51ABE-00000-000001 ┊ 2024-09-26 10:28:39 ┊ C|minis03 ┊ ImplementationError: Uncaught exception in j  ┊

root@minis01:~# linstor err show 66F51ABE-00000-000001
ERROR REPORT 66F51ABE-00000-000001

============================================================

Application:                        LINBIT®

Error message:                      Uncaught exception in j

Call backtrace:

    Method                                   Native Class:Line number
    run                                      N      com.linbit.linstor.spacetracking.j:312
    run                                      N      java.lang.Thread:840

Caused by:
==========

Category:                           RuntimeException
Class name:                         NullPointerException
Class canonical name:               java.lang.NullPointerException
Generated at:                       Method 'requireNonNull', Source file 'Objects.java', Line #235

Error message:                      value2

Call backtrace:

    Method                                   Native Class:Line number
    requireNonNull                           N      java.util.Objects:235
    <init>                                   N      reactor.util.context.Context3:47
    of                                       N      reactor.util.context.Context:92
    a                                        N      com.linbit.linstor.core.apicallhandler.controller.internal.a:113
    a                                        N      com.linbit.linstor.core.apicallhandler.controller.internal.a:83
    a                                        N      com.linbit.linstor.spacetracking.j:896
    c                                        N      com.linbit.linstor.spacetracking.j:560
    run                                      N      com.linbit.linstor.spacetracking.j:281
    run                                      N      java.lang.Thread:840

END OF ERROR REPORT.

After this event I have to do a

`systemctl restart linstor-controller` 

on the active Linstor controller node & the controller works again.

Following versions are installed:

dpkg-query -W linstor*
linstor-client  1.23.2-1

linstor-common  1.29.1-1

linstor-controller      1.29.1-1

linstor-proxmox 8.0.4-1

linstor-satellite       1.29.1-1

**Comment by rp-** [comment]
And until you restarted the controller nothing worked?
Or what exactly didn't work?

**Comment by SystemFuchs** [comment]
Proxmox will loose the connectivity to the devices if I do not restart the controller. The controller is not reachable

**Comment by SystemFuchs** [comment]
![image](https://github.com/user-attachments/assets/496c7164-7f8a-4ecb-997e-8f387776c70f)

**Comment by SystemFuchs** [comment]
**Configs:**

cat /etc/linstor/linstor-client.conf

```
[global]
controllers=192.168.178.201,192.168.178.202,192.168.178.203
```
cat /etc/drbd-reactor.d/linstor_db.toml

```
[[promoter]]
[promoter.resources.linstor_db]
start = ["var-lib-linstor.mount", "linstor-controller.service"]
on-drbd-demote-failure = "reboot"
stop-services-on-exit = true
target-as = "Requires"
```

cat /etc/pve/storage.cfg

```
drbd: linstor_storage_00
        resourcegroup pve-rg
        content rootdir,images
        controller 192.168.178.201,192.168.178.202,192.168.178.203

drbd: linstor_storage_01
        resourcegroup pve-rg1
        content images,rootdir
        controller 192.168.178.201,192.168.178.202,192.168.178.203
```

**Comment by ghernadi** [comment]
If you don't mind I would also take a look at other ErrorReports. Either gather `/var/log/linstor` from the nodes for me, or just send me an SOS report (via `linstor sos dl`) to the email address from my profile.

**Comment by ghernadi** [comment]
Thank you for the logs (both rounds :) ). I think I know what race-condition triggered there and if I am not mistaken it should be quite easy to fix. 

I'll close this issue for now, since I believe this should be a quite rare race-condition. Feel free (anyone) to reopen this issue if it happens again. 

One way to "protect" yourself against this race condition is to make sure that if the controller starts, all satellites can connect within the first 3 minutes. This race-condition requires at least 1 satellite to be offline exactly 3 minutes after the controller started.   
So even if you miss this time-window and trigger the issue again, please make sure the satellite can be reached (SystemFuch had a few other "Network is unreachable" errors that contributed to this issue) and restart the controller.   
The database should _not_ be affected at all by this issue.

Thanks for the report!
