### ISSUE TITLE
Error creating resources

### ISSUE THREAD

**Issue by brendanrjohnson** [LINBIT/linstor-server#45]
I get the following error when I try to create a resource on a storage node.  drbdadm is installed on the storage nodes.  The error report indicates that it is a timeout issue.

sudo linstor resource create stor02a stor02 --storage-pool pool_stor02

`SUCCESS:
Description:
    New resource 'stor02' on node 'stor02a' registered.
Details:
    Resource 'stor02' on node 'stor02a' UUID is: 392a2f54-3d21-4b2b-adf5-269dc0f4ee8c`
`SUCCESS:
Description:
    Volume with number '0' on resource 'stor02' on node 'stor02a' successfully registered
Details:
    Volume UUID is: b58a14e8-8a7c-4b4f-8c0b-cc2d0effd385`
`ERROR:
Description:
    (Node: 'stor02a') Adjusting the DRBD state of resource 'stor02' failed
Cause:
    The external command for adjusting the DRBD state of the resource failed
Correction:
    - Check whether the required software is installed
    - Check whether the application's search path includes the location
      of the external software
    - Check whether the application has execute permission for the external command
Show reports:
    linstor error-reports show 5C2CFB48-BB581-000002`

linstor error-reports show 5C2CFB48-BB581-000002

`ERROR REPORT 5C2CFB48-BB581-000002

============================================================

Application:                        LINBIT® LINSTOR
Module:                             Satellite
Version:                            0.7.5
Build ID:                           d74305b420fdc878182afa162378a317e6a4a3b9
Build time:                         2018-12-21T09:05:14+00:00
Error time:                         2019-01-02 13:02:21
Node:                               stor02a

============================================================

Reported error:
===============

Description:
    Operations on resource 'stor02' were aborted
Cause:
    The external command for adjusting the DRBD state of the resource failed
Correction:
    - Check whether the required software is installed
    - Check whether the application's search path includes the location
      of the external software
    - Check whether the application has execute permission for the external command

Category:                           LinStorException
Class name:                         ResourceException
Class canonical name:               com.linbit.linstor.core.DrbdDeviceHandler.ResourceException
Generated at:                       Method 'adjustResource', Source file 'DrbdDeviceHandler.java', Line #1559

Error message:                      Adjusting the DRBD state of resource 'stor02' failed

Error context:
    Adjusting the DRBD state of resource 'stor02' failed

Call backtrace:

    Method                                   Native Class:Line number
    adjustResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1559
    createResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1141
    dispatchResource                         N      com.linbit.linstor.core.DrbdDeviceHandler:364
    run                                      N      com.linbit.linstor.core.DeviceManagerImpl$DeviceHandlerInvocation:1229
    run                                      N      com.linbit.WorkerPool$WorkerThread:179

Caused by:
==========

Description:
    Execution of the external command 'drbdadm' failed.
Cause:
    The external command did not complete within the timeout.
    Possible causes include:
    - The system load may be too high to ensure completion of external commands in a timely manner.
    - The program implementing the external command may not be operating properly.
    - The operating system may have entered an errorneous state.
Correction:
    Check whether the external program and the operating system are still operating properly.
    Check whether the system's load is within normal parameters.
Additional information:
    The full command line executed was:
    drbdadm -vvv adjust stor02

Category:                           LinStorException
Class name:                         ExtCmdFailedException
Class canonical name:               com.linbit.extproc.ExtCmdFailedException
Generated at:                       Method 'execute', Source file 'DrbdAdm.java', Line #442

Error message:                      The external command 'drbdadm' did not complete within the timeout

Call backtrace:

    Method                                   Native Class:Line number
    execute                                  N      com.linbit.drbd.DrbdAdm:442
    adjust                                   N      com.linbit.drbd.DrbdAdm:95
    adjustResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1553
    createResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1141
    dispatchResource                         N      com.linbit.linstor.core.DrbdDeviceHandler:364
    run                                      N      com.linbit.linstor.core.DeviceManagerImpl$DeviceHandlerInvocation:1229
    run                                      N      com.linbit.WorkerPool$WorkerThread:179

Caused by:
==========

Category:                           Exception
Class name:                         ChildProcessTimeoutException
Class canonical name:               com.linbit.ChildProcessTimeoutException
Generated at:                       Method 'waitFor', Source file 'ChildProcessHandler.java', Line #133

Call backtrace:

    Method                                   Native Class:Line number
    waitFor                                  N      com.linbit.extproc.ChildProcessHandler:133
    syncProcess                              N      com.linbit.extproc.ExtCmd:92
    pipeExec                                 N      com.linbit.extproc.ExtCmd:63
    execute                                  N      com.linbit.drbd.DrbdAdm:434
    adjust                                   N      com.linbit.drbd.DrbdAdm:95
    adjustResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1553
    createResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1141
    dispatchResource                         N      com.linbit.linstor.core.DrbdDeviceHandler:364
    run                                      N      com.linbit.linstor.core.DeviceManagerImpl$DeviceHandlerInvocation:1229
    run                                      N      com.linbit.WorkerPool$WorkerThread:179

END OF ERROR REPORT.`

**Comment by raltnoeder** [comment]
Apparently, for whatever reason, the command `drbdadm -vvv adjust stor02` did not complete. This is probably caused by a bug in either drbd-utils or the DRBD kernel modules. `drbdadm` uses `drbdsetup` to adjust the state of a resource, and it normally issues a warning and exits if `drbdsetup` gets stuck. Obviously, that did not work in this case, so `drbdadm` itself hit the timeout in LINSTOR.

You can try to reproduce the problem, e.g. by running the same command manually to see whether or not that command completes successfully and within a 45 second time frame.
If it does not, it would be best to file a bug report for drbd-utils or DRBD (more likely DRBD, since `drbdsetup` commonly gets stuck due to DRBD being stuck). In that case, any kernel messages regarding the resource that causes the problem may be helpful.

**Comment by ghernadi** [comment]
Can you please repeat the test and post the kernel logs of Linstor's attempt here?
