### ISSUE TITLE
uppercase character in hostname

### ISSUE THREAD

**Issue by csecsi** [LINBIT/linstor-server#47]
Is it possible that uppercase characters confuse Linstore? 

[MainWorkerPool-1] ERROR LINSTOR/Satellite - Satellite node name 'LNQHSOpensT006' doesn't match nodes hostname 'LNQHSOpensT006'

**Comment by raltnoeder** [comment]
We found the cause of this problem, it is a bug in the Satellite's check of the local node name vs. the node name registered on the Controller. The code makes an incorrect attempt at performing a case-insensitive comparison.
The bug should be fixed in the v0.9.1 release.

**Comment by csecsi** [comment]
THX for the quick feedback (and for the fix). :)
