### ISSUE TITLE
Linstor resources ignore global_common.conf

### ISSUE THREAD

**Issue by jiri-lunacek** [LINBIT/linstor-server#49]
Linstor resource ignore all settings set in global _common_ section.

I have made some investigation and found out that when resource uses _template-file_ directive and the template file includes _common_ section it replaces the global _common_ section altogether.
linstor uses
`template-file "linstor_common.conf";`
in every resource file.

This would not be a problem, if linstor allowed all settings of DRBD to be set in _controller drbd-options_ but this is not the case (e.g. handlers).

I think that this should get some thought. IMO this renders linstor unusable for anyone who wants to use some advanced DRBD features.

**Comment by rp-** [comment]
You are right, handlers options were missing.

We have added them and they are now available in linstor-server 0.9.5/linstor-client 0.9.2

**Comment by jiri-lunacek** [comment]
Thanks for the update.

There is probably a flaw in implementation. Handler section appeared in linstor_common bud it is empty. Is there something I am missing? Do I need to upgrade database somehow?

```
LINSTOR ==> controller list-properties
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ Key                                       ┊ Value                                                                                        ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ DrbdOptions/Disk/read-balancing           ┊ least-pending                                                                                ┊
┊ DrbdOptions/Handlers/after-resync-target  ┊ /root/server/tools/drbd/unsnapshot-resync-target-lvm.sh; /usr/lib/drbd/crm-unfence-peer.9.sh ┊
┊ DrbdOptions/Handlers/before-resync-target ┊ /root/server/tools/drbd/snapshot-resync-target-lvm.sh -l daemon -t --                        ┊
┊ DrbdOptions/Handlers/fence-peer           ┊ /usr/lib/drbd/crm-fence-peer.9.sh                                                            ┊
┊ DrbdOptions/Handlers/out-of-sync          ┊ /usr/lib/drbd/notify-out-of-sync.sh root                                                     ┊
┊ DrbdOptions/Handlers/quorum-lost          ┊ /usr/lib/drbd/notify-quorum-lost.sh root                                                     ┊
┊ DrbdOptions/Handlers/split-brain          ┊ /usr/lib/drbd/notify-split-brain.sh root                                                     ┊
┊ DrbdOptions/Net/after-sb-0pri             ┊ discard-older-primary                                                                        ┊
┊ DrbdOptions/Net/after-sb-1pri             ┊ discard-secondary                                                                            ┊
┊ DrbdOptions/Net/after-sb-2pri             ┊ disconnect                                                                                   ┊
┊ DrbdOptions/Net/allow-two-primaries       ┊ yes                                                                                          ┊
┊ DrbdOptions/Net/fencing                   ┊ dont-care                                                                                    ┊
```
```
cat /var/lib/linstor.d/linstor_common.conf
# This file was generated by linstor(0.9.5), do not edit manually.

common
{
    disk
    {
        read-balancing least-pending;
    }

    handlers
    {
    }
    net
    {
        after-sb-0pri discard-older-primary;
        after-sb-1pri discard-secondary;
        after-sb-2pri disconnect;
        allow-two-primaries yes;
        fencing dont-care;
    }
}
```

**Comment by jiri-lunacek** [comment]
Ok. Another info update. After restarting linstor-satellite services the linstor_common.conf got updated.
Therefore now it seems that setting drbd-options does not trigger reconfiguration of the satellites.
Don't know if this is intentional or not.

**Comment by rp-** [comment]
no this is a bug, we could reproduce and have internally fixed.
It will be in the next version 0.9.6, also note that handlers will always be quoted in the config.

I guess from your property outputs that currently your generated resource configurations will not work.

**Comment by jiri-lunacek** [comment]
> I guess from your property outputs that currently your generated resource configurations will not work.

Yes. I can confirm. I had to force quote the values for the configuration to work.
