### ISSUE TITLE
error in Linstor Server compiled from sources: Failed to load database configuration

### ISSUE THREAD

**Issue by tiptop-labs** [LINBIT/linstor-server#50]
I have built the Linstor Server from [`linstor-server-0.9.5.tar.gz`](https://www.linbit.com/downloads/linstor/linstor-server-0.9.5.tar.gz) with `gradle getProtoc; gradle assemble`. This produces a tarball `build/distributions/linstor-server-0.9.5.tar`.

When I run the Linstor Server from this tarball with `tar xf linstor-server-0.9.5.tar; cd linstor-server-0.9.5; ./bin/Controller` it immediately exits with the following error:

> [Main] ERROR LINSTOR/Controller - Failed to load database configuration

Isn't an [external database](https://docs.linbit.com/docs/users-guide-9.0/#s-linstor-external-database) an optional choice for the Linstor Server? The entry points in the provided Dockerfiles suggest controllers (and satellites) normally receive a command line argument `--config-directory`. What should the content of such a directory be such that this error message goes away and the Linstor Server can start up normally?

**Comment by ghernadi** [comment]
Please check `scripts/postinstall.sh`.

You are correct that Linstor works with an embedded database (H2), but Linstor still needs a `database.cfg` which will be generated when you call `scripts/postinstall.sh`. The `database.cfg` is needed as you still have to specify where the H2 database files should be located.

**Comment by tiptop-labs** [comment]
P.S. `scripts/postinstall.sh` expects `/usr/share/linstor-server/bin/linstor-config`. Extracting the build output `build/distributions/linstor-server-0.9.5.tar` as `/usr/share/linstor-server`prior to running the script helps in that regard.
