### ISSUE TITLE
Storage exceptions on linstor-satellite requires restart of satellite and controller

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#53]
Problem is that if controller faced with the some exception on satellite node, this node is become to non operable state.

Node is still marked as **Online** but all resources is marked as **Unknown** on it. Controller will not try to reconnect with this satellite anymore until restart of satellite and controller itself.

**Comment by kvaps** [comment]
ref https://github.com/LINBIT/linstor-server/issues/52

**Comment by ghernadi** [comment]
As you have closed #52, is this issue also solved?

**Comment by kvaps** [comment]
Not exactly, sometimes controller is hanging on some operations, and if the was failed it is not trying to repeat them. I'm not totally sure, but I think any external command failure will cause this behavior.

Usual solution to fix that, restart linstor-satellite and linstor-controller services. Sometimes only linstor-controller is enough, and after that it is starting to work as it should.

Unfortunately can't reproduce it right now. But I will write here if I will face this problem again.

Thank you

**Comment by ghernadi** [comment]
> ...  sometimes controller is hanging on some operations, ...
Do you know / have an idea of what kind of operations are involved? Creating a resource? Connecting to satellites? Listing resources / storage-pool / ... ?

> and if the was failed it is not trying to repeat them
Usually the controller only tries to repeat failed resource creations. 

If you find some related ErrorReports, please attach them here.

**Comment by kvaps** [comment]
I've just ask'd my colleague about the details.

Usually this problem is connected with the deletion of diskless resources.

Sometimes after the deletion diskless replica, the data resources still have configured connections to the non-existing diskless resources. They have to be removed manually via drbdadm or they can be removed after restarting linstor-satellite, sometimes they can stuck in Unknown, so it also requires restart of the linstor-controller.

> If you find some related ErrorReports, please attach them here.
sure, next time I will do

**Comment by rp-** [comment]
failed resources should now get into a retry queue
