### ISSUE TITLE
Wrong size for diskless devices. 

### ISSUE THREAD

**Issue by krakazyabra** [LINBIT/linstor-server#64]
Hi!  
For diskless devices in `linstor sp l` i see empty values for TotalCapacity and FreeCapacity. But in json for these devices i see some wild values like exobyte:  
```        "driver": "DisklessDriver", 
        "free_space": {
          "free_capacity": 9223372036854775807, 
          "stor_pool_name": "diskless", 
          "total_capacity": 9223372036854775807
        }, 
```  
How to fix it to right values? These values make big mess in monitoring of storage pools.

**Comment by rp-** [comment]
We return Long.MAX_VALUE here which should express that a diskless pool doesn't use any storage or has infinite storage.
What would you expect? If you use the values in scripts you can filter diskless pools out by the driver: "DisklessDriver"

**Comment by rck** [comment]
Is this value used in internal calculations where it "has to be" a really big number for (non)-filtering (e.g., the autoplace logic)? Otherwise, IIRC, -1 is used  for some sizes as "don't know yet"/"does not apply". So for consistency I'd go for -1. And yes, one could argue if it is more like "infinity" than "does not apply", but if in doubt, I'd vote for one consistent value that flags these kinds of sizes. Which might be -1 for sizes.

**Comment by ghernadi** [comment]
It is indeed an internal thing, not for the autoplace logic, but for the more general question "does the storage pool have enough space for the resource/volume?" which is asked for all storage pools, regardless if they are diskless or not.
However, as this is only an internal thing we can definitely change the `free_capacity` and `total_capacity` of a diskless storage pool when asked by a client (like in the case of `linstor sp l`). I don't mind rck's suggestion of sending -1, but for me the question is still open if something like this would make sense.

We thought about sending a special value (like -1) for the diskless storage pool, but as rp- mentioned, we thought that LINSTOR-external scripts which also might want to perform some checks if the desired volume fits in the storage pool should be easier to implement if they get "infinity" (or rather a very large number) as something like -1.
