### ISSUE TITLE
linstor-controller 1.0.1 RuntimeException after reboot

### ISSUE THREAD

**Issue by netdox** [LINBIT/linstor-server#70]
On my debian 9 linstor-controller I get this Error after apt update/upgrade/reboot

> ERROR REPORT 5D5D3307-00000-000002
============================================================
Application:                        LINBIT® LINSTOR
Module:                             Controller
Version:                            1.0.1
Build ID:                           98a9905de43631b745c7c0741c2ef8f577513b23
Build time:                         2019-08-09T06:50:31+00:00
Error time:                         2019-08-21 14:03:24
Node:                               linstor-controller
Peer:                               Node: 'KVM-PB'
============================================================
Reported error:
===============
Category:                           RuntimeException
Class name:                         ErrorCallbackNotImplemented
Class canonical name:               reactor.core.Exceptions.ErrorCallbackNotImplemented
Generated at:                       <UNKNOWN>
Error message:                      com.linbit.ImplementationError: Unknown (proto) LayerType: UNRECOGNIZED
Call backtrace:
Method                                   Native Class:Line number
Caused by:
==========
Category:                           Error
Class name:                         ImplementationError
Class canonical name:               com.linbit.ImplementationError
Generated at:                       Method 'parseDeviceLayerKind', Source file 'ProtoDeserializationUtils.java', Line #162
Error message:                      Unknown (proto) LayerType: UNRECOGNIZED

Before update and reboot my node list was Online now

>╭────────────────────────────────────────────────────────╮
┊ Node               ┊ NodeType  ┊ Addresses                ┊ State   ┊
╞════════════════════════════════════════════════════════╡
┊ KVM-PA             ┊ SATELLITE ┊ XXX.XXX.XXX.XXX:3366 (PLAIN)  ┊ OFFLINE ┊
┊ KVM-PB             ┊ SATELLITE ┊  XXX.XXX.XXX.XXX:3366 (PLAIN)  ┊ OFFLINE ┊
┊ KVM-PC             ┊ SATELLITE ┊  XXX.XXX.XXX.XXX:3366 (PLAIN)  ┊ OFFLINE ┊
┊ linstor-controller ┊ COMBINED ┊  XXX.XXX.XXX.XXX:3366 (PLAIN) ┊ Online  ┊
╰────────────────────────────────────────────────────────╯

Anyone a idea why proto and layer now unkown?

Thx & best regards

**Comment by ghernadi** [comment]
Thanks for the report. I am pretty sure that we have already fixed this bug internally (will be included in the next release).
If I am correct with my guess, then you have different versions between your controller and the satellites. Please make sure that you have updated ALL linstor instances (controller and all satellites) to the same version.

If you have the same version on all linstor instances and still receive this error, please report here again.

**Comment by netdox** [comment]
Thanks @ghernadi  you're absolutely right. I didn't see that on the upgrade also linstor-* packages on the controller was updated. 
After I update the Version on the satellites and restart the linstor service on all satelltes and also restart the controller everything looks good. 

> ╭───────────────────────────-────────────────────────────────╮
┊ Node               ┊ NodeType  ┊ Addresses                ┊ State  ┊
╞════════════════════════════════════════════════════════════╡
┊ KVM-PA             ┊ SATELLITE ┊ XXX.XXX.XXX.XXX:3366 (PLAIN)  ┊ Online ┊
┊ KVM-PB             ┊ SATELLITE ┊ XXX.XXX.XXX.XXX:3366 (PLAIN)  ┊ Online ┊
┊ KVM-PC             ┊ SATELLITE ┊ XXX.XXX.XXX.XXX:3366 (PLAIN)  ┊ Online ┊
┊ linstor-controller ┊ COMBINED ┊ XXX.XXX.XXX.XXX:3366 (PLAIN) ┊ Online ┊
╰────────────────────────────────────────────────────────────╯
