### ISSUE TITLE
'resource delete' error

### ISSUE THREAD

**Issue by gen555** [LINBIT/linstor-server#73]
Hi!
I try to undeploy resource from a node.
`linstor resource delete hyper2 vm-apb-oper`
And get the message:

SUCCESS:
Description:
    Node: hyper2, Resource: vm-apb-oper marked for deletion.
Details:
    Node: hyper2, Resource: vm-apb-oper UUID is: 99afec46-037e-4c0f-92dd-798b83b21180
SUCCESS:
    Deleted 'vm-apb-oper' on 'hyper2'
ERROR:
    (Node: 'hyper1') Failed to adjust DRBD resource vm-apb-oper
Show reports:
    linstor error-reports show 5D695225-8FECE-000058

error-report shows:
...
Caused by:
Description:
    Execution of the external command 'drbdsetup' failed.
Cause:
    The external command exited with error code 5.
Correction:
    - Check whether the external program is operating properly.
    - Check whether the command line is correct.
      Contact a system administrator or a developer if the command line is no longer valid
      for the installed version of the external program.
Additional information:
    The full command line executed was:
    drbdsetup wait-connect-resource --wait-after-sb=yes --wfc-timeout=10 vm-apb-oper
The external command sent the following output data:

    The external command sent the following error information:
    degr-wfc-timeout has to be shorter than wfc-timeout
    degr-wfc-timeout implicitly set to wfc-timeout (10s)
    outdated-wfc-timeout has to be shorter than degr-wfc-timeout
    outdated-wfc-timeout implicitly set to degr-wfc-timeout (10s)
...

Versions:
kmod-drbd-9.0.19_4.14.35_1902.3.1.el7uek.x86_64-1.x86_64
linstor-controller-1.0.1-1.el7.noarch
python-linstor-1.0.0-1.noarch
linstor-satellite-1.0.1-1.el7.noarch
drbd-bash-completion-9.10.0-1.el7.x86_64
linstor-common-1.0.1-1.el7.noarch
drbd-udev-9.10.0-1.el7.x86_64
drbd-utils-9.10.0-1.el7.x86_64
linstor-client-1.0.1-1.noarch

linstor resource list:
┊ vm-apb-oper      ┊ hyper1 ┊ 7009 ┊ InUse  ┊ Resizing, UpToDate ┊
┊ vm-apb-oper      ┊ hyper2 ┊ 7009 ┊        ┊           DELETING ┊

Resizing command ends up with the same error-report description and mark resource as 'Resizing'.
linstor volume-definition set-size vm-apb-oper 1 210G
SUCCESS:
Description:
    Volume definition with number '1' of resource definition 'vm-apb-oper' modified.
Details:
    Volume definition with number '1' of resource definition 'vm-apb-oper' UUID is: 7fc9355a-66f2-42ba-8f3e-8edc8a6fc556
SUCCESS:
    Updated volume 1 of 'vm-apb-oper' on 'hyper2'
ERROR:
    (Node: 'hyper1') Failed to adjust DRBD resource vm-apb-oper
Show reports:
    linstor error-reports show 5D695225-8FECE-000076

I have no special configuration parameters in the resource config:
> # This file was generated by linstor(1.0.1), do not edit manually.
> 
> resource "vm-apb-oper"
> {
>     template-file "linstor_common.conf";
> 
>     net
>     {
>         cram-hmac-alg     sha1;
>         shared-secret     "nTJ089ZhpfTOdEM/pfFI";
>         allow-two-primaries no;
>         on-congestion pull-ahead;
>         protocol C;
>         sndbuf-size 0;
>         verify-alg sha1;
>     }
> 
>     disk
>     {
>         read-balancing prefer-local;
>     }
> 
>     on hyper1
>     {
>         volume 0
>         {
>             disk        /dev/drbdpool/vm-apb-oper_00;
>             meta-disk   internal;
>             device      minor 114;
>         }
>         volume 1
>         {
>             disk        /dev/drbdpool/vm-apb-oper_01;
>             meta-disk   internal;
>             device      minor 115;
>         }
>         node-id    0;
>     }
> }
> 

So the resource is undeployed, no drbd connections and lvm volumes on remote host, but it still exists in linstor DB because drbdsetup error.
How can I delete resource from linstor DB?

**Comment by gen555** [comment]
As addition. Other resource deploys/undeploys without errors.

**Comment by rp-** [comment]
The last resize delete fix we did was in 1.29.1, so if you are on an older version than that, you might try upgrade.
Otherwise you will probably have to remove the resize flag in the database.

**Comment by dimm0** [comment]
I'm on 1.29.2

Can I get a hint how to fix the database? Which crd?

**Comment by ghernadi** [comment]
Before you try to fix the database, I would try to do both, possibly multiple times in combination:
* Try to re-issue the resize
* Try to delete one resource after the other. That means do not use `rd d` but rather `r d ...` (ideally diskless resources first).


If that does not help, before you edit the database: **Make a BACKUP** of the database, so you can always restore if something goes wrong.

The `RESIZE` flag is on VolumeDefinition and Volume level, see https://github.com/LINBIT/linstor-server/blob/7383057ff3f9acc2b4053f6998e687363a1ffc8a/server/src/main/java/com/linbit/linstor/core/objects/VolumeDefinition.java#L584-L590 as well as https://github.com/LINBIT/linstor-server/blob/7383057ff3f9acc2b4053f6998e687363a1ffc8a/server/src/main/java/com/linbit/linstor/core/objects/Volume.java#L491-L499 
The flags are just single bits in one combined `long` field in the database.

If you want to get rid of the `DELETE` flags, you need to check ResourceDefinition, VolumeDefinition, Resource and Volume levels. In addition to the above two links:
https://github.com/LINBIT/linstor-server/blob/7383057ff3f9acc2b4053f6998e687363a1ffc8a/server/src/main/java/com/linbit/linstor/core/objects/ResourceDefinition.java#L747-L752
https://github.com/LINBIT/linstor-server/blob/7383057ff3f9acc2b4053f6998e687363a1ffc8a/server/src/main/java/com/linbit/linstor/core/objects/Resource.java#L614-L663

**Comment by dimm0** [comment]
<img width="1346" alt="Image" src="https://github.com/user-attachments/assets/d3db472f-05d6-4dc4-a274-db94431d4b2e" />

I have it working ok on one node, absent in config (drbdadm..) but present in DB on another node, and the rest are broken.
Resizing changes the size on the 2nd node. As I understand that's the primary replica.

```
root@linstor-controller-64564c5897-m9bnv:/# linstor rd lp pvc-8432f744-eb35-45a2-83af-303db62ca1bc
╭──────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ Key                                    ┊ Value                                                       ┊
╞══════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ Aux/csi-provisioning-completed-by      ┊ linstor-csi/v1.1.0-20969df70962927a06cbdf714e9ca8cc3912cb4d ┊
┊ DrbdOptions/Resource/quorum            ┊ off                                                         ┊
┊ DrbdOptions/auto-add-quorum-tiebreaker ┊ false                                                       ┊
┊ DrbdOptions/auto-quorum                ┊ disabled                                                    ┊
┊ DrbdOptions/auto-verify-alg            ┊ sha256                                                      ┊
┊ DrbdPrimarySetOn                       ┊ RCI-NRP-DTN-02.SDSU.EDU                                     ┊
┊ FileSystem/MkfsParams                  ┊                                                             ┊
┊ FileSystem/Type                        ┊ xfs                                                         ┊
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

Maybe I could somehow change the primary replica to the 1st node? (sorry for hijacking the issue, I can open a new one...)
