### ISSUE TITLE
Zfs Clones?

### ISSUE THREAD

**Issue by SVronskiy** [LINBIT/linstor-server#78]
Hello!
Does LinStor support making some zfs read-write clones from one snapshot?
Any plans to support clonning via kubernetes yamls?

Regards, Sergey

**Comment by SVronskiy** [comment]
May be it is possible to create ZFS ZVOL inside PVC?

**Comment by raltnoeder** [comment]
I am not sure I understood what the question is. LINSTOR can create ZFS volumes, it can take snapshots of those volumes, and it can create new volumes from a snapshot or reset a volume to the state of a snapshot. It does not deal with anything kubernetes, that's what the CSI driver does, so I guess this question may be better directed at the linstor-csi project.

**Comment by SVronskiy** [comment]
Thank you! I've added question at [linstor-csi](https://github.com/LINBIT/linstor-csi/issues/38)
