### ISSUE TITLE
Provide Kubernetes ready API for Aggregation Layer

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#81]
Hi,

*Sorry if I chose wrong project for creating this issue. At first I was created this issue on [piraeus project](https://github.com/piraeusdatastore/project/issues/2), but this project have no any watchers, so I'm not sure that someone saw it there.*

Any way this feature request is mainly for the discussion. I've decided that it might be interesting for you so better I will compact my thoughts here.

We're using Linstor on Kubernetes and quite happy about that. The only problem is that Linstor requires some configuration and management from our side.

I wrote [own operator](https://github.com/kvaps/kube-linstor) for configure Linstor in our clusters, eg we have the next CRDs in our cluster:

```bash
# kubectl get linstorcontrollers
NAME         AGE
controller   49d

# kubectl get linstornodes
NAME   STATUS   ADDRESSES
m1c4   ONLINE   10.28.36.164
m1c5   ONLINE   10.28.36.165
m1c6   ONLINE   10.28.36.166
m1c7   ONLINE   10.28.36.167
m1c8   ONLINE   10.28.36.168
m1c9   ONLINE   10.28.36.169
pve1   ONLINE   10.28.36.159
pve2   ONLINE   10.28.36.160
pve3   ONLINE   10.28.36.161

# kubectl get linstorstoragepools                                                                                                                                                                                
NAME            STATUS   DRIVER     POOLNAME   FREE        TOTAL       SNAPSHOTS
data.m1c4       OK       LVM                   60862464    937689088   false
data.m1c5       OK       LVM                   61915136    937689088   false
data.m1c6       OK       LVM                   60760064    937689088   false
data.m1c7       OK       LVM                   20176896    937689088   false
data.m1c8       OK       LVM                   45342720    937689088   false
data.m1c9       OK       LVM                   754425856   937689088   false
diskless.m1c4   OK       DISKLESS                                      false
diskless.m1c5   OK       DISKLESS                                      false
diskless.m1c6   OK       DISKLESS                                      false
diskless.m1c7   OK       DISKLESS                                      false
diskless.m1c8   OK       DISKLESS                                      false
diskless.m1c9   OK       DISKLESS                                      false
diskless.pve1   OK       DISKLESS                                      false
diskless.pve2   OK       DISKLESS                                      false
diskless.pve3   OK       DISKLESS                                      false
pve.pve1        OK       LVM                   626917376   937426944   false
pve.pve2        OK       LVM                   515661824   937426944   false
pve.pve3        OK       LVM                   626810880   937426944   false
thindata.m1c4   OK       LVM_THIN              600372674   838860800   true
thindata.m1c5   OK       LVM_THIN              600708218   838860800   true
thindata.m1c6   OK       LVM_THIN              618324295   838860800   true
thindata.m1c7   OK       LVM_THIN              599449927   838860800   true
thindata.m1c8   OK       LVM_THIN              554738647   838860800   true
```

It is quite useful to list all the resources created in linstor using kubectl, and check their state.
Also you can easily automate creating of them just describing each of them in Kubernetes cluster.

As can I see Piraeus-operator uses the same logic, but provides configuration in more condensed form, it is [`PiraeusControllerSet`](https://github.com/piraeusdatastore/piraeus-operator/blob/master/deploy/crds/piraeus_v1alpha1_piraeuscontrollerset_cr.yaml) and [`PiraeusNodeSet`](https://github.com/piraeusdatastore/piraeus-operator/blob/master/deploy/crds/piraeus_v1alpha1_piraeuscontrollerset_cr.yaml).

But linstor-server have really beautiful rest API, and similar logic with Kubernetes. It handles creating and removing objects the same way like it Kubernetes is doing that.
From other side Kubernetes provides cool option to integrate with it.
Currently It can be achieved by two ways:
1. creating [CRDs and operator for it](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) (Like peraeus-operator do)
2. adding [Kubernetes API-like server for handling requests directly](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/).

In my opinion Kubernetes and Linstor it two platforms which will conquer the market more and more. (I actively participate in this, eg. talk about linstor in my public speeches and etc. 🙂)
So my idea is to integrate Linstor with Kubernetes fully, using API Integration layer.

It might be useful for automate linstor configuration, operating only Kubernetes resources. It also can always provide an actual information about storagepool, linstor nodes and the rest resources.

And it does not requires custom controller for translate Kubernetes'es Custom Resources to Linstor and back.
Linstor can provide kubernetes-like api out of box or having some service proxy for that.

So user will be able to operate with linstor directly via Kubernetes.

What is your opinion about this?

**Comment by raltnoeder** [comment]
Apart from the technical details regarding integration of multiple APIs (long story short, the API in the current version of LINSTOR is actually more monolithic than in older versions, e.g. no more dynamic loading of API calls, and the reasons are a long story that has virtually nothing to do with technology...), I am not a big fan of introducing product-specific special cases directly into the LINSTOR Controller if it is avoidable, because it adds a lot of bloat compared to having external connector modules.

I also doubt that it would fit very well, because there are a couple translation-layers between Kubernetes and LINSTOR to connect those two products, since LINSTOR has its own rules regarding nodes, resources, snapshots, etc., and those rules are not compatible with Kubernetes' rules (most of LINSTOR's rules are stricter), so some things like certain names in Kubernetes must be translated to be usable with LINSTOR. Therefore, adding an API that has semantics that do not match LINSTOR's design does not seem to make too much sense. It would get even more confusing once the same is demanded for other projects, and we end up having an OpenStack-API, OpenNebula-API, etc. as well.

It may be more convenient for each specific use case, but I doubt that it enhances the quality of product as a whole in the long run. I would rather keep the LINSTOR API generic and clean and keep the specifics for certain products that use LINSTOR isolated in the respective connector modules.

**Comment by kvaps** [comment]
>  since LINSTOR has its own rules regarding nodes, resources, snapshots, etc., and those rules are not compatible with Kubernetes' rules (most of LINSTOR's rules are stricter), so some things like certain names in Kubernetes must be translated to be usable with LINSTOR.

Extending the Kubernetes API with the aggregation layer is only the representation of objects by providing familiar API for Kubernetes. All the rules and logic of creation of objects remains on the LINSTOR side, eg you could create new linstor-nodes and storage-pools by simple uploading yaml-objects into Kubernetes, you can see the status of them by executing `kubectl get linstornodes`. All the calls will be translated directly into LINSTOR, so  if creating was failed by some reason you always will immediately get an error from LINSTOR server, without waiting when pending resource will be processed by external operator.

> It would get even more confusing once the same is demanded for other projects, and we end up having an OpenStack-API, OpenNebula-API, etc. as well.

No one of these projects have no such powerful extension system with CRDs and API-server aggregation as Kubernetes have.

> It may be more convenient for each specific use case, but I doubt that it enhances the quality of product as a whole in the long run. I would rather keep the LINSTOR API generic and clean and keep the specifics for certain products that use LINSTOR isolated in the respective connector modules.

I'm not arguing 🙂
Mainly this question was to Piraeus project which is developing own operator for the managing LINSTOR. I just wanted to draw your attention to consider this option as an alternative to writing own operator.

Thank you
