### ISSUE TITLE
ERROR: Too many layered resources!

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#82]
Hi, we faced with the cluster limits set by default on linstor:

```
ERROR:
Description:
    Too many layered resources!
Cause:
    null
Details:
    Node(s): 'm14c45', Resource: 'test'
Show reports:
    linstor error-reports show 5DA8107D-00000-000050
```

[ErrorReport-5DA8107D-00000-000050.log](https://github.com/LINBIT/linstor-server/files/3744179/ErrorReport-5DA8107D-00000-000050.log)

```bash
linstor -m r l | jq '.[].resources | length' 
2876
```

```bash
linstor -m rd l | jq '.[].rsc_dfns | length'
1002
```

Looks like Linstor have limit for 1000 resources definitions, the newly created resource definitions does not get the ports, this is contradicts what was said here:
https://lists.linbit.com/pipermail/drbd-user/2019-June/025074.html

Is there any option to increase the cluster limits or reuse allocated ports?

**Comment by kvaps** [comment]
It seems I found how to solve my problem:

```
linstor controller set-property TcpPortAutoRange 7000-9999
```

the default values are set to:

https://github.com/LINBIT/linstor-server/blob/4a378b22af144a2bf99174db69813bdaad1e2b01/server/src/main/java/com/linbit/linstor/numberpool/NumberPoolModule.java#L38-L39

**Comment by rck** [comment]
exactly

**Comment by raltnoeder** [comment]
Reopening. I have opened an internal issue to fix the error message.
The cause should say that the TCP port number pool is exhausted (and it certainly should not ever say "null", this is an implementation error), and the correction field should be present and should hint at setting TcpPortAutoRange. That's what those fields were intended for in the first place.
Internal issue nr. is 439
