### ISSUE TITLE
linstor is not handling replicas-on-different for existing resources

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#88]
```
# linstor v l -r one-image-1915
+------------------------------------------------------------------------------------------------------------+
| Node   | Resource       | StoragePool | VolumeNr | MinorNr | DeviceName    | Allocated | InUse  |    State |
|============================================================================================================|
| m13c37 | one-image-1915 | thindata    | 0        | 1370    | /dev/drbd1370 | 20.01 GiB | Unused | UpToDate |
+------------------------------------------------------------------------------------------------------------+
```

```
# linstor n lp m13c37
+----------------------------+
| Key              | Value   |
|============================|
| Aux/moonshot     | 13      |
| Aux/opennebula-1 | true    |
| CurStltConnName  | default |
| NodeUname        | m13c37  |
+----------------------------+
```

```
# linstor r c one-image-1915 --auto-place 2 --replicas-on-same opennebula-1 --replicas-on-different moonshot -s thindata
SUCCESS:
Description:
    Resource 'one-image-1915' successfully autoplaced on 1 nodes
Details:
    Used storage pool: 'thindata'
    Used nodes: 'm13c20'
SUCCESS:
    Added peer(s) 'm13c20' to resource 'one-image-1915' on 'm13c37'
SUCCESS:
    Created resource 'one-image-1915' on 'm13c20'
SUCCESS:
Description:
    Resource 'one-image-1915' on 'm13c20' ready
Details:
    Auto-placing resource: one-image-1915
```

```
# linstor v l -r one-image-1915
+----------------------------------------------------------------------------------------------------------------------+
| Node   | Resource       | StoragePool | VolumeNr | MinorNr | DeviceName    | Allocated | InUse  |              State |
|======================================================================================================================|
| m13c20 | one-image-1915 | thindata    | 0        | 1370    | /dev/drbd1370 | 2.37 GiB  | Unused | SyncTarget(20.58%) |
| m13c37 | one-image-1915 | thindata    | 0        | 1370    | /dev/drbd1370 | 20.01 GiB | Unused |           UpToDate |
+----------------------------------------------------------------------------------------------------------------------+
```

```
# linstor n lp m13c20
+----------------------------+
| Key              | Value   |
|============================|
| Aux/moonshot     | 13      |
| Aux/opennebula-1 | true    |
| CurStltConnName  | default |
| NodeUname        | m13c20  |
+----------------------------+
```

as you can see, linstor have created both resource on nodes with `Aux/moonshot=13` unlike requested `--replicas-on-different moonshot`

**Comment by ghernadi** [comment]
I agree, this is a bug.

The actual bug is that the auto-select algorithm only cares about its own choice, not about the choice already made by existing replica.

However, fixing this might not be that trivial as "simply pre-seeding the filters" for `--replicas-on-different` and `--replicas-on-same`. Although this might work for the "on-different" case, but surely raises at least the question "what would you expect to happen when you do `--replicas-on-same mykey` where you already have 2 replicas with different values for `Aux/mykey`?"
Error? One of the already existing? Anything else?

**Comment by kvaps** [comment]
To tell the truth I like how is it implemented in Kubernetes where any pod, this is a minimum unit in our abstraction (in our case drbd-resource), can be created by user or by upstream controller: eg. ReplicaSet or StatefulSet (in our case it might be Resource Definition).

When user creating pod manually he can assign nodeAffinity rules to the pod directly.
In case when pod is created by upstream abstraction nodeAffinity will always be inherited from it.

Linstor have little different logic, but we can go the same way:
1) to allow user create resources manually and do not rely on existing ones
2) existing resources can be managed by upstream abstraction eg. by resource definitions, it can watch for always needed amount of replicas created with needed parameters.

PS: I am still little confused about resources groups, may be this is exactly this abstraction that we need, but if I understood it well it is just set of parameters used for spawn new resources.

Cheers!

**Comment by kvaps** [comment]
Probably solved by implementing resource-groups?
